In [1]:
import pandas as pd
import numpy as np
import pickle

pd.set_option("display.max_columns",None)

In [2]:
flights = pd.read_csv("flights.csv")

C:\Users\gfine\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3326: DtypeWarning: Columns (7,8) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [5]:
len(flights)

5819079

In [6]:
flights.dropna(subset = ["ORIGIN_AIRPORT"], inplace = True)
len(flights)

5819079

In [10]:
flights["ORIGIN_AIRPORT"] = flights["ORIGIN_AIRPORT"].astype(str)
flights["DESTINATION_AIRPORT"] = flights["DESTINATION_AIRPORT"].astype(str)

In [12]:
flights["code"] = flights["ORIGIN_AIRPORT"] + flights["DESTINATION_AIRPORT"]

In [31]:
# Buscamos aquellos códigos de aeropuerto que no sean con IATA_CODE tipo str
unknown = flights[flights["code"].str.isdigit()].copy()
unknown.head()

YEAR  MONTH  DAY  DAY_OF_WEEK AIRLINE  FLIGHT_NUMBER TAIL_NUMBER  \
4385712  2015     10    1            4      AA           1230      N3DBAA   
4385713  2015     10    1            4      DL           1805      N696DL   
4385714  2015     10    1            4      NK            612      N602NK   
4385715  2015     10    1            4      AA            260      N3GNAA   
4385716  2015     10    1            4      AA           1982      N914UY   

        ORIGIN_AIRPORT DESTINATION_AIRPORT  SCHEDULED_DEPARTURE  \
4385712          14747               11298                    5   
4385713          14771               13487                    5   
4385714          12889               13487                    5   
4385715          12892               13303                   10   
4385716          14771               11057                   10   

         DEPARTURE_TIME  DEPARTURE_DELAY  TAXI_OUT  WHEELS_OFF  \
4385712            15.0             10.0      15.0        30.0   
4385713            16.0             11.0      14.0        30.0   
4385714          2400.0             -5.0      15.0        15.0   
4385715             7.0             -3.0      28.0        35.0   
4385716             8.0             -2.0      12.0        20.0   

         SCHEDULED_TIME  ELAPSED_TIME  AIR_TIME  DISTANCE  WHEELS_ON  TAXI_IN  \
4385712           237.0         208.0     189.0      1660      539.0      4.0   
4385713           213.0         192.0     171.0      1589      521.0      7.0   
4385714           177.0         168.0     149.0      1299      444.0      4.0   
4385715           296.0         306.0     271.0      2342      806.0      7.0   
4385716           291.0         282.0     257.0      2296      737.0     13.0   

         SCHEDULED_ARRIVAL  ARRIVAL_TIME  ARRIVAL_DELAY  DIVERTED  CANCELLED  \
4385712                602         543.0          -19.0         0          0   
4385713                538         528.0          -10.0         0          0   
4385714                502         448.0          -14.0         0          0   
4385715                806         813.0            7.0         0          0   
4385716                801         750.0          -11.0         0          0   

        CANCELLATION_REASON  AIR_SYSTEM_DELAY  SECURITY_DELAY  AIRLINE_DELAY  \
4385712                 NaN               NaN             NaN            NaN   
4385713                 NaN               NaN             NaN            NaN   
4385714                 NaN               NaN             NaN            NaN   
4385715                 NaN               NaN             NaN            NaN   
4385716                 NaN               NaN             NaN            NaN   

         LATE_AIRCRAFT_DELAY  WEATHER_DELAY        code  
4385712                  NaN            NaN  1474711298  
4385713                  NaN            NaN  1477113487  
4385714                  NaN            NaN  1288913487  
4385715                  NaN            NaN  1289213303  
4385716                  NaN            NaN  1477111057

In [32]:
# Hay que clasificar 306 aeropuertos
unknown['ORIGIN_AIRPORT'].nunique()

306

In [36]:
unknown = unknown.sort_values('ORIGIN_AIRPORT')
unknown['ORIGIN_AIRPORT'].unique()

array(['10135', '10136', '10140', '10141', '10146', '10154', '10155',
       '10157', '10158', '10165', '10170', '10185', '10208', '10257',
       '10268', '10279', '10299', '10333', '10372', '10397', '10408',
       '10423', '10431', '10434', '10469', '10529', '10551', '10561',
       '10577', '10581', '10599', '10620', '10627', '10631', '10685',
       '10693', '10713', '10721', '10728', '10731', '10732', '10739',
       '10747', '10754', '10779', '10781', '10785', '10792', '10800',
       '10821', '10849', '10868', '10874', '10918', '10926', '10980',
       '10990', '10994', '11003', '11013', '11042', '11049', '11057',
       '11066', '11067', '11076', '11097', '11109', '11111', '11122',
       '11140', '11146', '11150', '11193', '11203', '11252', '11259',
       '11267', '11274', '11278', '11292', '11298', '11308', '11315',
       '11337', '11413', '11423', '11433', '11447', '11471', '11481',
       '11503', '11525', '11537', '11540', '11577', '11587', '11603',
       '11612', '116

In [17]:
# Ningun trayecto da lugar a dos distancias diferentes
unknown.groupby("code")["DISTANCE"].nunique().max()

1

In [22]:
# Diccionario que relaciona un trayecto y su distancia
dict_flight_distance = dict(zip(unknown["code"],unknown["DISTANCE"]))
dict_flight_distance

{'1474711298': 1660,
 '1477113487': 1589,
 '1288913487': 1299,
 '1289213303': 2342,
 '1477111057': 2296,
 '1477113930': 1846,
 '1289213930': 1744,
 '1486911057': 1727,
 '1289211298': 1235,
 '1289213487': 1535,
 '1289210693': 1797,
 '1289211057': 2125,
 '1029914747': 1448,
 '1288912266': 1222,
 '1474713487': 1399,
 '1477112266': 1635,
 '1129212478': 1626,
 '1410711298': 868,
 '1474713930': 1721,
 '1029914057': 1542,
 '1486910397': 1590,
 '1477111298': 1464,
 '1289212266': 1379,
 '1288911298': 1055,
 '1288913198': 1139,
 '1129211057': 1337,
 '1163014747': 1533,
 '1288912173': 2762,
 '1073211618': 1585,
 '1425413204': 1179,
 '1014113487': 257,
 '1062713487': 386,
 '1198211298': 134,
 '1217312402': 216,
 '1410712266': 1009,
 '1393013303': 1197,
 '1468311298': 247,
 '1226613303': 964,
 '1161811298': 1372,
 '1072113930': 867,
 '1072111298': 1562,
 '1348711298': 852,
 '1161811057': 529,
 '1072111057': 728,
 '1072113303': 1258,
 '1188414747': 224,
 '1393011298': 802,
 '1591911298': 280,
 '1385

Busco IATA_CODE de aeropuerto

In [42]:
pocho = flights[flights["ORIGIN_AIRPORT"] == '12255']
pocho.head()

# siempre a aeropuerto destino: 11292
#distance = 298 

YEAR  MONTH  DAY  DAY_OF_WEEK AIRLINE  FLIGHT_NUMBER TAIL_NUMBER  \
4390906  2015     10    1            4      OO           5428      N919SW   
4398680  2015     10    1            4      OO           5341      N594SW   
4407536  2015     10    2            5      OO           5428      N964SW   
4415293  2015     10    2            5      OO           5341      N913SW   
4425343  2015     10    3            6      OO           5428      N507CA   

        ORIGIN_AIRPORT DESTINATION_AIRPORT  SCHEDULED_DEPARTURE  \
4390906          12255               11292                 1016   
4398680          12255               11292                 1758   
4407536          12255               11292                 1016   
4415293          12255               11292                 1758   
4425343          12255               11292                 1240   

         DEPARTURE_TIME  DEPARTURE_DELAY  TAXI_OUT  WHEELS_OFF  \
4390906          1009.0             -7.0       9.0      1018.0   
4398680          1748.0            -10.0       6.0      1754.0   
4407536          1101.0             45.0       9.0      1110.0   
4415293          1836.0             38.0      11.0      1847.0   
4425343          1236.0             -4.0      10.0      1246.0   

         SCHEDULED_TIME  ELAPSED_TIME  AIR_TIME  DISTANCE  WHEELS_ON  TAXI_IN  \
4390906            74.0          76.0      59.0       298     1017.0      8.0   
4398680            74.0          68.0      54.0       298     1748.0      8.0   
4407536            74.0          65.0      52.0       298     1102.0      4.0   
4415293            74.0          77.0      56.0       298     1843.0     10.0   
4425343            74.0          64.0      50.0       298     1236.0      4.0   

         SCHEDULED_ARRIVAL  ARRIVAL_TIME  ARRIVAL_DELAY  DIVERTED  CANCELLED  \
4390906               1030        1025.0           -5.0         0          0   
4398680               1812        1756.0          -16.0         0          0   
4407536               1030        1106.0           36.0         0          0   
4415293               1812        1853.0           41.0         0          0   
4425343               1254        1240.0          -14.0         0          0   

        CANCELLATION_REASON  AIR_SYSTEM_DELAY  SECURITY_DELAY  AIRLINE_DELAY  \
4390906                 NaN               NaN             NaN            NaN   
4398680                 NaN               NaN             NaN            NaN   
4407536                 NaN              36.0             0.0            0.0   
4415293                 NaN               3.0             0.0            0.0   
4425343                 NaN               NaN             NaN            NaN   

         LATE_AIRCRAFT_DELAY  WEATHER_DELAY        code  
4390906                  NaN            NaN  1225511292  
4398680                  NaN            NaN  1225511292  
4407536                  0.0            0.0  1225511292  
4415293                 38.0            0.0  1225511292  
4425343                  NaN            NaN  1225511292

In [44]:
pocho_dist = flights[flights["DISTANCE"] == 298]
pocho_dist

YEAR  MONTH  DAY  DAY_OF_WEEK AIRLINE  FLIGHT_NUMBER TAIL_NUMBER  \
786      2015      1    1            4      OO           5428      N679SA   
4400     2015      1    1            4      OO           5417      N947SW   
4414     2015      1    1            4      OO           7381      N675BR   
6003     2015      1    1            4      OO           7381      N675BR   
7063     2015      1    1            4      OO           5411      N947SW   
...       ...    ...  ...          ...     ...            ...         ...   
5810716  2015     12   31            4      OO           5428      N920SW   
5811239  2015     12   31            4      OO           7381      N455CA   
5812803  2015     12   31            4      OO           7381      N455CA   
5814846  2015     12   31            4      OO           5424      N946SW   
5816910  2015     12   31            4      OO           5346      N946SW   

        ORIGIN_AIRPORT DESTINATION_AIRPORT  SCHEDULED_DEPARTURE  \
786                HYS                 DEN                  650   
4400               DEN                 HYS                 1110   
4414               SLC                 COD                 1112   
6003               COD                 SLC                 1252   
7063               HYS                 DEN                 1357   
...                ...                 ...                  ...   
5810716            HYS                 DEN                 1035   
5811239            SLC                 COD                 1112   
5812803            COD                 SLC                 1252   
5814846            DEN                 HYS                 1514   
5816910            HYS                 DEN                 1753   

         DEPARTURE_TIME  DEPARTURE_DELAY  TAXI_OUT  WHEELS_OFF  \
786               650.0              0.0      23.0       713.0   
4400             1100.0            -10.0      10.0      1110.0   
4414             1112.0              0.0      17.0      1129.0   
6003             1319.0             27.0       7.0      1326.0   
7063             1347.0            -10.0       7.0      1354.0   
...                 ...              ...       ...         ...   
5810716          1025.0            -10.0       7.0      1032.0   
5811239          1105.0             -7.0      14.0      1119.0   
5812803          1245.0             -7.0      36.0      1321.0   
5814846          1525.0             11.0      14.0      1539.0   
5816910          1745.0             -8.0      23.0      1808.0   

         SCHEDULED_TIME  ELAPSED_TIME  AIR_TIME  DISTANCE  WHEELS_ON  TAXI_IN  \
786                74.0          85.0      53.0       298      706.0      9.0   
4400               77.0          64.0      47.0       298     1257.0      7.0   
4414               75.0          78.0      57.0       298     1226.0      4.0   
6003               75.0          61.0      48.0       298     1414.0      6.0   
7063               74.0          63.0      50.0       298     1344.0      6.0   
...                 ...           ...       ...       ...        ...      ...   
5810716            80.0          70.0      59.0       298     1031.0      4.0   
5811239            75.0          67.0      47.0       298     1206.0      6.0   
5812803            75.0          91.0      50.0       298     1411.0      5.0   
5814846            67.0          59.0      42.0       298     1721.0      3.0   
5816910            80.0          88.0      59.0       298     1807.0      6.0   

         SCHEDULED_ARRIVAL  ARRIVAL_TIME  ARRIVAL_DELAY  DIVERTED  CANCELLED  \
786                    704         715.0           11.0         0          0   
4400                  1327        1304.0          -23.0         0          0   
4414                  1227        1230.0            3.0         0          0   
6003                  1407        1420.0           13.0         0          0   
7063                  1411        1350.0          -21.0         0          0   
...                    ...       

In [46]:
print(pocho_dist['ORIGIN_AIRPORT'].unique())
print(pocho_dist['DESTINATION_AIRPORT'].unique())

['HYS' 'DEN' 'SLC' 'COD' 'DCA' 'SYR' '11292' '12255' '14869' '11097']
['DEN' 'HYS' 'COD' 'SLC' 'SYR' 'DCA' '12255' '11292' '11097' '14869']


In [23]:
# Voy a tratar de identificar esta ruta '1474711298'

origen = '14747'
destino = '11298'

# Paso 1: Busco todas las rutas con distancia exactamente igual a 1660

# Pongo que el destino tampoco sea aeropuerto de salida para evitar el trayecto de misma distancia y origen distinto,
# Es decir, el trayecto que sale del aeropuerto 11298 y llega al aeropuerto 14747
rutas = flights[(flights["DISTANCE"] == 1660) & (flights["ORIGIN_AIRPORT"] != origen) & (flights["ORIGIN_AIRPORT"] != destino)].copy()
rutas["ORIGIN_AIRPORT"].value_counts()

DFW    3547
SEA    3545
Name: ORIGIN_AIRPORT, dtype: int64

Busco un codigo de ruta (origen+destino) asociado al orgigen numerico 14747 pero no al destino numerico

In [24]:
# Con este primer paso tengo ya dos claves que puedo asociar a dos numeros distintos, ahora solo falta saber cual es cual

# Paso 2 Busco otro vuelo que comience con el aeropuerto 14747, voy a elegir solo 1

[path for path in dict_flight_distance.keys() if (path[:5]== origen) & (path[-5:] != destino)][0]

'1474713487'

In [25]:
# Ahora voy a buscar las rutas alternativas que tengo desde ese aeropuerto
alternativa = flights[(flights["DISTANCE"] == dict_flight_distance['1474713487']) & (flights["ORIGIN_AIRPORT"] != origen) & (flights["ORIGIN_AIRPORT"] != '13487')].copy()
alternativa["ORIGIN_AIRPORT"].value_counts()

MSP    2549
SEA    2547
Name: ORIGIN_AIRPORT, dtype: int64

En este momento, estaría en condiciones de deducir que el código 14747 es el aeropuerto SEA, el código 11298 sería el DFW y
el código 13487 se lo asociaria a MSP 

In [27]:
# Con este esquema vamos a intentar montar un algoritmo que repita este proceso en todas las rutas disponibles, considerando
# que hay un poco (bastante) más de complejidad en las casuísticas.

# Tenemos por una parte una lista de rutas y tenemos un diccionario que relaciona la ruta con su distancia
dict_flight_distance = dict(zip(unknown["code"],unknown["DISTANCE"]))
paths = [path for path in dict_flight_distance.keys()]

# Creamos una estructura para almacenar los resultados, en este caso un diccionario clave:valor --> numero:aeropuerto
dict_airport = {}

# Elementos base que vamos a utilizar en el algoritmo
path = paths[0]

# Hasta que no sea capaz de clasificar todas las rutas no voy a parar
while paths != []:
    print(path)
    origen = path[:5]
    destino = path[-5:]
    path_inverso = destino + origen
    conjunto_paths = set(paths)
    
    # Primer caso: El origen no se encuentra en el diccionario, es decir, no hay un aeropuerto asociado
    if origen not in dict_airport.keys():
        
        # Busco las opciones de trayecto que me puedo encontrar con esta distancia
        ruta = flights[(flights["DISTANCE"] == dict_flight_distance[path]) & (flights["ORIGIN_AIRPORT"] != origen) & (flights["ORIGIN_AIRPORT"] != destino)].copy()
        opciones = [airport for airport in ruta["ORIGIN_AIRPORT"].unique().tolist() if (not airport.startswith('1')) and (airport not in dict_airport.values())]
        print(f"Las opciones para el origen de la ruta {path} son: {opciones}")
        
        # Si solo existe una opcion para el origen, se la asigno directamente
        # Esto solo puede pasar si el destino ya esta asignado por un path previo
        if len(opciones) == 1:
            dict_airport[origen] = opciones[0]
            
            # Elimino el path resultante ya que origen y destino están ya en el diccionario 
            paths.remove(path)
            
            # Si existe el camino inverso también lo voy a quitar puesto que no merece la pena compararlo
            if path_inverso in paths:
                paths.remove(path_inverso)

        # Si existieran dos o más opciones para el origen buscamos en rutas alternativas posibles puntos comunes
        # como en el ejemplo de arriba
        elif len(opciones) >= 2:
            rutas_alternativas = [path for path in paths if (path[:5]== origen) & (path[-5:] != destino)]

            # Si no existieran rutas alternativas hay que saltar este caso porque tampoco podría encontrar el match de momento
            if rutas_alternativas == []:
                print("No existen más rutas alternativas para este path {}".format(path))
                paths.remove(path)
                paths.append(path)
                path = paths[0]
                continue

            # Busco una ruta alternativa que me permita hacer el match
            
            # Estas dos constantes me sirven para dar cierta seguridad al match, no sirve con tener una ruta alternativa
            # coincidente si no que voy a mirar algunas más
            counter = 0
            coincidencias_requeridas = np.ceil(len(rutas_alternativas)/4)
            for i in range(len(rutas_alternativas)):
                ruta_alternativa = rutas_alternativas[i]
                alternativa = flights[(flights["DISTANCE"] == dict_flight_distance[ruta_alternativa]) & (flights["ORIGIN_AIRPORT"] != origen) & (flights["ORIGIN_AIRPORT"] != ruta_alternativa[-5:])].copy()
                posibilidades = [airport for airport in alternativa["ORIGIN_AIRPORT"].unique().tolist() if (not airport.startswith('1')) and (airport not in dict_airport.values())]
                print(f"Las posibilidades encontradas para el origen de la ruta alternativa {ruta_alternativa} son: {posibilidades}")

                coincidencias = [airport for airport in posibilidades if airport in opciones]
                print(f"Las coincidencias encontradas para el origen en la ruta alternativa {ruta_alternativa} son: {coincidencias}")
                if len(coincidencias) == 1:
                    counter += 1
                    if counter >= coincidencias_requeridas:
                        break
                else:
                    continue
            
        
            print(f"La ruta alternativa final es: {ruta_alternativa}")    

            # Si tras recorrer todas las rutas, no puedo encontrar una que me permita el match, tengo que saltar
            # a otro path, puesto que este no tendría seguridad para inferirlo
            if len(coincidencias) != 1:
                print("No se puede clasificar la ruta {} de momento, por no tener seguridad suficiente con la que hacer match".format(path))
                paths.remove(path)
                paths.append(path)
                path = paths[0]
                continue
         
            # En caso de poder hacer un match para el origen, busco la coincidencia y asigno 
            nuevo_destino = ruta_alternativa[-5:]
            ruta_alternativa_inversa = nuevo_destino + origen

            dict_airport[origen] = coincidencias[0]

            # Si la ruta me lo permite, busco clasificar la otra opción (siempre y cuando haya exactamente dos posibilidades)
            if (destino not in dict_airport.keys()) and (len(opciones) == 2):
                dict_airport[destino] = [airport for airport in opciones if airport != coincidencias[0]][0]
                
                paths.remove(path)
                
                if path_inverso in paths:
                    paths.remove(path_inverso)
            
            # De nuevo, si la ruta alternativa me lo permite, intento clasificar este segundo destino (debe haber exactamente
            # dos posibilidades)
            if (nuevo_destino not in dict_airport.keys()) and (len(posibilidades) == 2):
                dict_airport[nuevo_destino] = [airport for airport in posibilidades if airport != coincidencias[0]][0]

                paths.remove(ruta_alternativa)

                if ruta_alternativa_inversa in paths:
                    paths.remove(ruta_alternativa_inversa)
            
        
    # Segundo caso: Me falta por saber el destino del path    
    elif destino not in dict_airport.keys():
        
        # En este caso entendemos que el origen ya existe dentro del diccionario por lo que realizo la búsqueda para el 
        # destino solamente
        ruta = flights[(flights["DISTANCE"] == dict_flight_distance[path]) & (flights["ORIGIN_AIRPORT"] != origen) & (flights["ORIGIN_AIRPORT"] != destino)].copy()
        opciones = [airport for airport in ruta["ORIGIN_AIRPORT"].unique().tolist() if (not airport.startswith('1')) and (airport not in dict_airport.values())]
        print(f"Las opciones para el destino de la ruta {path} son: {opciones}")
        
        # Razono de la misma manera, si las opciones son más de dos busco una ruta alternativa
        if len(opciones) >= 2:
            # Busco una ruta alternativa que me permita hacer el match con respecto al destino del path
            rutas_alternativas = [path for path in paths if (path[:5]== destino) & (path[-5:] != origen)]
            
            # Si no existieran rutas alternativas hay que saltar este caso porque tampoco podría encontrar el match de momento
            if rutas_alternativas == []:
                print("No existen más rutas alternativas para este path {}".format(path))
                paths.remove(path)
                paths.append(path)
                path = paths[0]
                continue

            counter = 0
            coincidencias_requeridas = np.ceil(len(rutas_alternativas)/4)
            for i in range(len(rutas_alternativas)):
                ruta_alternativa = rutas_alternativas[i]
                alternativa = flights[(flights["DISTANCE"] == dict_flight_distance[ruta_alternativa]) & (flights["ORIGIN_AIRPORT"] != destino) & (flights["ORIGIN_AIRPORT"] != ruta_alternativa[-5:])].copy()
                posibilidades = [airport for airport in alternativa["ORIGIN_AIRPORT"].unique().tolist() if (not airport.startswith('1')) and (airport not in dict_airport.values())]
                print(f"Las posibilidades encontradas para el destino en la ruta alternativa {ruta_alternativa} son: {posibilidades}")
                coincidencias = [airport for airport in posibilidades if airport in opciones]
                print(f"Las coincidencias encontradas para el destino en la ruta alternativa {ruta_alternativa} son: {coincidencias}")
                
                if len(coincidencias) == 1:
                    counter += 1
                    if counter >= coincidencias_requeridas:
                        break
                else:
                    continue
            
            print(f"La ruta alternativa final es: {ruta_alternativa}")   
        
            # Si tras recorrer todas las rutas, no puedo encontrar una que me permita el match, tengo que saltar a otra
            if counter < coincidencias_requeridas:
                print("No se puede clasificar la ruta {} de momento, por no encontrar una ruta alternativa con la que hacer match".format(path))
                paths.remove(path)
                paths.append(path)
                path = paths[0]
                continue
                
            dict_airport[destino] = coincidencias[0]
        
        # Si solo existiera una opcion, se la agrego directamente
        else:
            dict_airport[destino] = opciones[0]

        paths.remove(path)

        if path_inverso in paths:
            paths.remove(path_inverso)
            
    # En el caso de que origen y destino ya hayan sido clasificados por otras rutas diferentes, esta comparación no
    # tiene sentido y solo necesitamos quitarla
    # Ejemplo de este caso: Tengo dos rutas, una que va de A a B y que ha sido clasificada, otra que va de C a D que también
    # ha sido clasificada. Si luego me encuentro la ruta que va de A a C, no necesito clasificarla.
    else:
        paths.remove(path)
        
        if path_inverso in paths:
            paths.remove(path_inverso)
            
    # Mensajes de estado del proceso    
    aeropuertos_clasificados = len(dict_airport.keys())
    rutas_por_clasificar = len(paths)
    path = paths[0]
    print("Aeropuertos clasificados: {}".format(aeropuertos_clasificados))
    print("Rutas por clasificar: {}".format(rutas_por_clasificar))
    
    if len(paths) % 20 == 0:
        print(dict_airport)    

1474711298
Las opciones para el origen de la ruta 1474711298 son: ['SEA', 'DFW']
Las posibilidades encontradas para el origen de la ruta alternativa 1474713487 son: ['SEA', 'MSP']
Las coincidencias encontradas para el origen en la ruta alternativa 1474713487 son: ['SEA']
Las posibilidades encontradas para el origen de la ruta alternativa 1474713930 son: ['SEA', 'ORD']
Las coincidencias encontradas para el origen en la ruta alternativa 1474713930 son: ['SEA']
Las posibilidades encontradas para el origen de la ruta alternativa 1474714107 son: ['SEA', 'PHX', 'STT', 'MIA', 'FLL', 'LGA', 'MCI']
Las coincidencias encontradas para el origen en la ruta alternativa 1474714107 son: ['SEA']
Las posibilidades encontradas para el origen de la ruta alternativa 1474714771 son: ['MSO', 'SEA', 'SFO', 'DEN', 'ACY', 'ATL']
Las coincidencias encontradas para el origen en la ruta alternativa 1474714771 son: ['SEA']
Las posibilidades encontradas para el origen de la ruta alternativa 1474711292 son: ['SEA', 

Las posibilidades encontradas para el origen de la ruta alternativa 1289211057 son: ['LAX', 'CLT', 'SLC', 'ANC']
Las coincidencias encontradas para el origen en la ruta alternativa 1289211057 son: ['LAX']
Las posibilidades encontradas para el origen de la ruta alternativa 1289212266 son: ['LAX', 'IAH']
Las coincidencias encontradas para el origen en la ruta alternativa 1289212266 son: ['LAX']
Las posibilidades encontradas para el origen de la ruta alternativa 1289211292 son: ['DEN', 'LAX', 'GSP', 'IAH']
Las coincidencias encontradas para el origen en la ruta alternativa 1289211292 son: ['LAX']
Las posibilidades encontradas para el origen de la ruta alternativa 1289210397 son: ['LAX', 'ATL']
Las coincidencias encontradas para el origen en la ruta alternativa 1289210397 son: ['LAX']
Las posibilidades encontradas para el origen de la ruta alternativa 1289214107 son: ['LAX', 'PHX']
Las coincidencias encontradas para el origen en la ruta alternativa 1289214107 son: ['LAX']
Las posibilidades

Las posibilidades encontradas para el destino en la ruta alternativa 1393011618 son: ['ORD', 'EWR', 'DCA', 'SDF', 'MCO', 'STL']
Las coincidencias encontradas para el destino en la ruta alternativa 1393011618 son: ['ORD']
Las posibilidades encontradas para el destino en la ruta alternativa 1393011042 son: ['MFE', 'IAH', 'CLE', 'ORD']
Las coincidencias encontradas para el destino en la ruta alternativa 1393011042 son: ['ORD']
Las posibilidades encontradas para el destino en la ruta alternativa 1393010431 son: ['AVL', 'ORD', 'MCI']
Las coincidencias encontradas para el destino en la ruta alternativa 1393010431 son: ['ORD']
Las posibilidades encontradas para el destino en la ruta alternativa 1393013487 son: ['ORD']
Las coincidencias encontradas para el destino en la ruta alternativa 1393013487 son: ['ORD']
Las posibilidades encontradas para el destino en la ruta alternativa 1393011066 son: ['LIT', 'CMH', 'BUR', 'SYR', 'ORD', 'DTW', 'DAL', 'LGA', 'ORF', 'ATW', 'ROC', 'LEX']
Las coincidencia

Las posibilidades encontradas para el destino en la ruta alternativa 1226610397 son: ['ATL', 'IAH', 'MCI', 'MSY']
Las coincidencias encontradas para el destino en la ruta alternativa 1226610397 son: ['IAH']
Las posibilidades encontradas para el destino en la ruta alternativa 1226614107 son: ['PDX', 'PHX', 'IAH', 'HDN']
Las coincidencias encontradas para el destino en la ruta alternativa 1226614107 son: ['IAH']
Las posibilidades encontradas para el destino en la ruta alternativa 1226614771 son: ['IAH']
Las coincidencias encontradas para el destino en la ruta alternativa 1226614771 son: ['IAH']
Las posibilidades encontradas para el destino en la ruta alternativa 1226613487 son: ['IAH', 'ISP', 'TPA', 'EWR', 'SRQ']
Las coincidencias encontradas para el destino en la ruta alternativa 1226613487 son: ['IAH']
Las posibilidades encontradas para el destino en la ruta alternativa 1226614100 son: ['PHL', 'IAH', 'OKC', 'EWR']
Las coincidencias encontradas para el destino en la ruta alternativa 122

Las posibilidades encontradas para el origen de la ruta alternativa 1129214771 son: ['MCI', 'DEN', 'BWI']
Las coincidencias encontradas para el origen en la ruta alternativa 1129214771 son: ['DEN']
Las posibilidades encontradas para el origen de la ruta alternativa 1129210693 son: ['DEN']
Las coincidencias encontradas para el origen en la ruta alternativa 1129210693 son: ['DEN']
Las posibilidades encontradas para el origen de la ruta alternativa 1129210821 son: ['BWI', 'DEN']
Las coincidencias encontradas para el origen en la ruta alternativa 1129210821 son: ['DEN']
Las posibilidades encontradas para el origen de la ruta alternativa 1129214869 son: ['COD', 'DEN', 'PNS', 'RNO']
Las coincidencias encontradas para el origen en la ruta alternativa 1129214869 son: ['DEN']
Las posibilidades encontradas para el origen de la ruta alternativa 1129213198 son: ['MCI', 'EWR', 'DEN', 'DAY', 'ATL', 'BMI', 'DTW', 'DSM']
Las coincidencias encontradas para el origen en la ruta alternativa 1129213198 so

Las posibilidades encontradas para el destino en la ruta alternativa 1039710821 son: ['BWI', 'ATL', 'MDW', 'GSP']
Las coincidencias encontradas para el destino en la ruta alternativa 1039710821 son: ['ATL']
Las posibilidades encontradas para el destino en la ruta alternativa 1039713232 son: ['ATL', 'MDW']
Las coincidencias encontradas para el destino en la ruta alternativa 1039713232 son: ['ATL']
Las posibilidades encontradas para el destino en la ruta alternativa 1039712191 son: ['HOU', 'ATL', 'STL']
Las coincidencias encontradas para el destino en la ruta alternativa 1039712191 son: ['ATL']
Las posibilidades encontradas para el destino en la ruta alternativa 1039711057 son: ['ATL', 'SNA']
Las coincidencias encontradas para el destino en la ruta alternativa 1039711057 son: ['ATL']
Las posibilidades encontradas para el destino en la ruta alternativa 1039711259 son: ['ATL', 'DAL', 'EGE', 'AUS', 'STL']
Las coincidencias encontradas para el destino en la ruta alternativa 1039711259 son: [

Las opciones para el destino de la ruta 1288913198 son: ['MCI', 'STX']
Las posibilidades encontradas para el destino en la ruta alternativa 1319813930 son: ['MCI', 'CVG', 'MEM']
Las coincidencias encontradas para el destino en la ruta alternativa 1319813930 son: ['MCI']
Las posibilidades encontradas para el destino en la ruta alternativa 1319811259 son: ['MCI', 'DAL', 'DTW', 'GSO']
Las coincidencias encontradas para el destino en la ruta alternativa 1319811259 son: ['MCI']
Las posibilidades encontradas para el destino en la ruta alternativa 1319813232 son: ['DCA', 'DTW', 'MDW', 'MCI', 'ACK']
Las coincidencias encontradas para el destino en la ruta alternativa 1319813232 son: ['MCI']
Las posibilidades encontradas para el destino en la ruta alternativa 1319814869 son: ['TPA', 'PHL', 'HOU', 'MCI']
Las coincidencias encontradas para el destino en la ruta alternativa 1319814869 son: ['MCI']
Las posibilidades encontradas para el destino en la ruta alternativa 1319810821 son: ['MCI', 'BWI']
L

Las posibilidades encontradas para el origen de la ruta alternativa 1188414869 son: ['BUF', 'ISN', 'DAL', 'STL', 'GEG']
Las coincidencias encontradas para el origen en la ruta alternativa 1188414869 son: ['GEG']
La ruta alternativa final es: 1188414869
Aeropuertos clasificados: 33
Rutas por clasificar: 3824
1188414747
Aeropuertos clasificados: 33
Rutas por clasificar: 3822
1393011298
Aeropuertos clasificados: 33
Rutas por clasificar: 3820
{'14747': 'SEA', '11298': 'DFW', '14831': 'SJC', '14771': 'SFO', '13487': 'MSP', '12889': 'LAS', '12892': 'LAX', '12264': 'IAD', '13303': 'MIA', '11057': 'CLT', '13930': 'ORD', '14869': 'SLC', '10693': 'BNA', '10299': 'ANC', '12266': 'IAH', '11292': 'DEN', '12478': 'JFK', '14107': 'PHX', '14057': 'PDX', '10397': 'ATL', '13198': 'MCI', '11630': 'FAI', '12173': 'HNL', '10732': 'BQN', '11618': 'EWR', '14254': 'PSE', '13204': 'MCO', '10627': 'BIS', '11982': 'GRK', '12402': 'ITO', '14683': 'SAT', '10721': 'BOS', '11884': 'GEG'}
1591911298
Las opciones para

Las opciones para el destino de la ruta 1217313830 son: ['OGG', 'RIC']
Las posibilidades encontradas para el destino en la ruta alternativa 1383012402 son: ['OGG']
Las coincidencias encontradas para el destino en la ruta alternativa 1383012402 son: ['OGG']
Las posibilidades encontradas para el destino en la ruta alternativa 1383012982 son: ['CRP', 'PIT', 'LFT', 'LIH', 'OGG', 'DTW']
Las coincidencias encontradas para el destino en la ruta alternativa 1383012982 son: ['OGG']
Las posibilidades encontradas para el destino en la ruta alternativa 1383014831 son: ['OGG']
Las coincidencias encontradas para el destino en la ruta alternativa 1383014831 son: ['OGG']
Las posibilidades encontradas para el destino en la ruta alternativa 1383014679 son: ['SAN', 'OGG']
Las coincidencias encontradas para el destino en la ruta alternativa 1383014679 son: ['OGG']
La ruta alternativa final es: 1383014679
Aeropuertos clasificados: 41
Rutas por clasificar: 3800
{'14747': 'SEA', '11298': 'DFW', '14831': 'SJC

Las posibilidades encontradas para el origen de la ruta alternativa 1537614679 son: ['TUS', 'DAY', 'SAN']
Las coincidencias encontradas para el origen en la ruta alternativa 1537614679 son: ['TUS']
Las posibilidades encontradas para el origen de la ruta alternativa 1537611292 son: ['TUS']
Las coincidencias encontradas para el origen en la ruta alternativa 1537611292 son: ['TUS']
Las posibilidades encontradas para el origen de la ruta alternativa 1537610397 son: ['TUS']
Las coincidencias encontradas para el origen en la ruta alternativa 1537610397 son: ['TUS']
La ruta alternativa final es: 1537610397
Aeropuertos clasificados: 46
Rutas por clasificar: 3786
1537612266
Aeropuertos clasificados: 46
Rutas por clasificar: 3784
1425412478
Aeropuertos clasificados: 46
Rutas por clasificar: 3782
1177811298
Las opciones para el origen de la ruta 1177811298 son: ['FSM', 'TRI', 'DCA', 'RDU']
Las posibilidades encontradas para el origen de la ruta alternativa 1177810397 son: ['FSM']
Las coincidencia

Las opciones para el origen de la ruta 1163713487 son: ['BUR', 'FNT', 'TLH', 'FAR']
Las posibilidades encontradas para el origen de la ruta alternativa 1163713930 son: ['FAR', 'SUN', 'CLE', 'MYR']
Las coincidencias encontradas para el origen en la ruta alternativa 1163713930 son: ['FAR']
La ruta alternativa final es: 1163713930
Aeropuertos clasificados: 51
Rutas por clasificar: 3770
1163713487
Aeropuertos clasificados: 51
Rutas por clasificar: 3768
1484211298
Las opciones para el origen de la ruta 1484211298 son: ['SJT', 'CVG', 'DTW', 'LGA']
No existen más rutas alternativas para este path 1484211298
1015511298
Las opciones para el origen de la ruta 1015511298 son: ['ACT', 'SBA', 'GJT']
No existen más rutas alternativas para este path 1015511298
1177513930
Las opciones para el origen de la ruta 1177513930 son: ['FSD', 'RDM', 'PIT', 'PIB']
Las posibilidades encontradas para el origen de la ruta alternativa 1177513487 son: ['CID', 'MTJ', 'FSD', 'HYA', 'BDL']
Las coincidencias encontradas

Las opciones para el origen de la ruta 1063113487 son: ['BJI', 'RDD', 'JNU', 'YAK', 'ACK']
No existen más rutas alternativas para este path 1063113487
1315812266
Las opciones para el origen de la ruta 1315812266 son: ['MAF']
Aeropuertos clasificados: 58
Rutas por clasificar: 3734
1410813930
Las opciones para el origen de la ruta 1410813930 son: ['RDU', 'PIA']
Las posibilidades encontradas para el origen de la ruta alternativa 1410812266 son: ['CMH', 'DSM', 'ASE', 'PIA']
Las coincidencias encontradas para el origen en la ruta alternativa 1410812266 son: ['PIA']
La ruta alternativa final es: 1410812266
Aeropuertos clasificados: 59
Rutas por clasificar: 3734
1410813930
Aeropuertos clasificados: 59
Rutas por clasificar: 3732
1393011697
Las opciones para el destino de la ruta 1393011697 son: ['MSY', 'FLL', 'SAN', 'DAL']
Las posibilidades encontradas para el destino en la ruta alternativa 1169710397 son: ['FLL']
Las coincidencias encontradas para el destino en la ruta alternativa 1169710397 

Las opciones para el origen de la ruta 1562410397 son: ['VPS', 'ACV', 'DRO']
Las posibilidades encontradas para el origen de la ruta alternativa 1562412266 son: ['VPS', 'CAK', 'ELP', 'SCE', 'ROC', 'DTW', 'GRR']
Las coincidencias encontradas para el origen en la ruta alternativa 1562412266 son: ['VPS']
La ruta alternativa final es: 1562412266
Aeropuertos clasificados: 65
Rutas por clasificar: 3706
1562410397
Aeropuertos clasificados: 65
Rutas por clasificar: 3704
1074712266
Las opciones para el origen de la ruta 1074712266 son: ['BRO', 'CVG']
Las posibilidades encontradas para el origen de la ruta alternativa 1074711298 son: ['BRO', 'PWM']
Las coincidencias encontradas para el origen en la ruta alternativa 1074711298 son: ['BRO']
La ruta alternativa final es: 1074711298
Aeropuertos clasificados: 66
Rutas por clasificar: 3704
1074712266
Aeropuertos clasificados: 66
Rutas por clasificar: 3702
1541111298
Las opciones para el origen de la ruta 1541111298 son: ['TYR']
Aeropuertos clasificado

Las opciones para el origen de la ruta 1496011298 son: ['SPS', 'LAR', 'AZO', 'DTW']
No existen más rutas alternativas para este path 1496011298
1227813930
Las opciones para el origen de la ruta 1227813930 son: ['OAK', 'LGB', 'SNA', 'ICT', 'IND']
Las posibilidades encontradas para el origen de la ruta alternativa 1227810397 son: ['ICT']
Las coincidencias encontradas para el origen en la ruta alternativa 1227810397 son: ['ICT']
Las posibilidades encontradas para el origen de la ruta alternativa 1227812266 son: ['ICT']
Las coincidencias encontradas para el origen en la ruta alternativa 1227812266 son: ['ICT']
La ruta alternativa final es: 1227812266
Aeropuertos clasificados: 75
Rutas por clasificar: 3680
{'14747': 'SEA', '11298': 'DFW', '14831': 'SJC', '14771': 'SFO', '13487': 'MSP', '12889': 'LAS', '12892': 'LAX', '12264': 'IAD', '13303': 'MIA', '11057': 'CLT', '13930': 'ORD', '14869': 'SLC', '10693': 'BNA', '10299': 'ANC', '12266': 'IAH', '11292': 'DEN', '12478': 'JFK', '14107': 'PHX', 

Las posibilidades encontradas para el destino en la ruta alternativa 1323212889 son: ['MDW']
Las coincidencias encontradas para el destino en la ruta alternativa 1323212889 son: ['MDW']
Las posibilidades encontradas para el destino en la ruta alternativa 1323211066 son: ['CMH', 'BDL', 'MDW']
Las coincidencias encontradas para el destino en la ruta alternativa 1323211066 son: ['MDW']
Las posibilidades encontradas para el destino en la ruta alternativa 1323214100 son: ['MDW', 'DTW', 'PWM']
Las coincidencias encontradas para el destino en la ruta alternativa 1323214100 son: ['MDW']
La ruta alternativa final es: 1323214100
Aeropuertos clasificados: 81
Rutas por clasificar: 3652
1289211292
Aeropuertos clasificados: 81
Rutas por clasificar: 3650
1319811259
Las opciones para el destino de la ruta 1319811259 son: ['DAL', 'DTW']
Las posibilidades encontradas para el destino en la ruta alternativa 1125910397 son: ['DAL', 'EGE']
Las coincidencias encontradas para el destino en la ruta alternativa

Las posibilidades encontradas para el destino en la ruta alternativa 1014014771 son: ['MKE', 'ABQ', 'TTN']
Las coincidencias encontradas para el destino en la ruta alternativa 1014014771 son: ['MKE', 'ABQ']
Las posibilidades encontradas para el destino en la ruta alternativa 1014011298 son: ['ABQ', 'CVG', 'RST']
Las coincidencias encontradas para el destino en la ruta alternativa 1014011298 son: ['ABQ']
Las posibilidades encontradas para el destino en la ruta alternativa 1014010397 son: ['PSP', 'ABQ']
Las coincidencias encontradas para el destino en la ruta alternativa 1014010397 son: ['ABQ']
Las posibilidades encontradas para el destino en la ruta alternativa 1014012889 son: ['ABQ']
Las coincidencias encontradas para el destino en la ruta alternativa 1014012889 son: ['ABQ']
La ruta alternativa final es: 1014012889
Aeropuertos clasificados: 85
Rutas por clasificar: 3634
1323212892
Aeropuertos clasificados: 85
Rutas por clasificar: 3632
1329615304
Las opciones para el origen de la ruta 

Las posibilidades encontradas para el origen de la ruta alternativa 1452411433 son: ['LBB', 'DTW', 'RIC', 'LBE']
Las coincidencias encontradas para el origen en la ruta alternativa 1452411433 son: ['RIC']
Las posibilidades encontradas para el origen de la ruta alternativa 1452412953 son: ['RIC', 'LGA']
Las coincidencias encontradas para el origen en la ruta alternativa 1452412953 son: ['RIC']
Las posibilidades encontradas para el origen de la ruta alternativa 1452410721 son: ['RIC', 'SDF', 'LBB']
Las coincidencias encontradas para el origen en la ruta alternativa 1452410721 son: ['RIC']
La ruta alternativa final es: 1452410721
Aeropuertos clasificados: 90
Rutas por clasificar: 3616
1452411057
Aeropuertos clasificados: 90
Rutas por clasificar: 3614
1474712892
Aeropuertos clasificados: 90
Rutas por clasificar: 3612
1221710397
Las opciones para el origen de la ruta 1221710397 son: ['HSV']
Aeropuertos clasificados: 91
Rutas por clasificar: 3610
1071313487
Las opciones para el origen de la 

Las opciones para el origen de la ruta 1106610821 son: ['CMH']
Aeropuertos clasificados: 100
Rutas por clasificar: 3576
1289214107
Aeropuertos clasificados: 100
Rutas por clasificar: 3574
1289611259
Las opciones para el origen de la ruta 1289611259 son: ['MLU', 'LBB']
Las posibilidades encontradas para el origen de la ruta alternativa 1289610423 son: ['JAN', 'LBB']
Las coincidencias encontradas para el origen en la ruta alternativa 1289610423 son: ['LBB']
Las posibilidades encontradas para el origen de la ruta alternativa 1289612266 son: ['IDA', 'LBB']
Las coincidencias encontradas para el origen en la ruta alternativa 1289612266 son: ['LBB']
La ruta alternativa final es: 1289612266
Aeropuertos clasificados: 101
Rutas por clasificar: 3574
1289611259
Aeropuertos clasificados: 101
Rutas por clasificar: 3572
1039710821
Aeropuertos clasificados: 101
Rutas por clasificar: 3570
1039713232
Aeropuertos clasificados: 101
Rutas por clasificar: 3568
1069313232
Aeropuertos clasificados: 101
Rutas 

Las opciones para el origen de la ruta 1327710397 son: ['MGM', 'DBQ']
Las posibilidades encontradas para el origen de la ruta alternativa 1327711298 son: ['MGM', 'CLE']
Las coincidencias encontradas para el origen en la ruta alternativa 1327711298 son: ['MGM']
La ruta alternativa final es: 1327711298
Aeropuertos clasificados: 107
Rutas por clasificar: 3534
1327710397
Aeropuertos clasificados: 107
Rutas por clasificar: 3532
1197710397
Aeropuertos clasificados: 107
Rutas por clasificar: 3530
1120313930
Las opciones para el origen de la ruta 1120313930 son: ['TOL', 'YAK', 'CDV', 'CWA', 'CLE']
No existen más rutas alternativas para este path 1120313930
1489311292
Aeropuertos clasificados: 107
Rutas por clasificar: 3528
1410012266
Aeropuertos clasificados: 107
Rutas por clasificar: 3526
1219115016
Aeropuertos clasificados: 107
Rutas por clasificar: 3524
1319813232
Aeropuertos clasificados: 107
Rutas por clasificar: 3522
1069312191
Aeropuertos clasificados: 107
Rutas por clasificar: 3520
{'1

Las opciones para el origen de la ruta 1295313303 son: ['LGA']
Aeropuertos clasificados: 110
Rutas por clasificar: 3500
{'14747': 'SEA', '11298': 'DFW', '14831': 'SJC', '14771': 'SFO', '13487': 'MSP', '12889': 'LAS', '12892': 'LAX', '12264': 'IAD', '13303': 'MIA', '11057': 'CLT', '13930': 'ORD', '14869': 'SLC', '10693': 'BNA', '10299': 'ANC', '12266': 'IAH', '11292': 'DEN', '12478': 'JFK', '14107': 'PHX', '14057': 'PDX', '10397': 'ATL', '13198': 'MCI', '11630': 'FAI', '12173': 'HNL', '10732': 'BQN', '11618': 'EWR', '14254': 'PSE', '13204': 'MCO', '10627': 'BIS', '11982': 'GRK', '12402': 'ITO', '14683': 'SAT', '10721': 'BOS', '11884': 'GEG', '15919': 'XNA', '13851': 'OKC', '11111': 'COU', '12191': 'HOU', '14783': 'SGF', '15016': 'STL', '12758': 'KOA', '13830': 'OGG', '10423': 'AUS', '15370': 'TUL', '11953': 'GNV', '13891': 'ONT', '15376': 'TUS', '11778': 'FSM', '11278': 'DCA', '14100': 'PHL', '15304': 'TPA', '11637': 'FAR', '11775': 'FSD', '12982': 'LIH', '13931': 'ORF', '10821': 'BWI',

Las opciones para el origen de la ruta 1104211298 son: ['CLE']
Aeropuertos clasificados: 115
Rutas por clasificar: 3474
1509610397
Las opciones para el origen de la ruta 1509610397 son: ['PNS', 'SYR']
Las posibilidades encontradas para el origen de la ruta alternativa 1509612478 son: ['FAT', 'SYR']
Las coincidencias encontradas para el origen en la ruta alternativa 1509612478 son: ['SYR']
Las posibilidades encontradas para el origen de la ruta alternativa 1509611433 son: ['LIT', 'SYR']
Las coincidencias encontradas para el origen en la ruta alternativa 1509611433 son: ['SYR']
La ruta alternativa final es: 1509611433
Aeropuertos clasificados: 116
Rutas por clasificar: 3474
1509610397
Aeropuertos clasificados: 116
Rutas por clasificar: 3472
1072111433
Aeropuertos clasificados: 116
Rutas por clasificar: 3470
1040810397
Las opciones para el origen de la ruta 1040810397 son: ['ATW']
Aeropuertos clasificados: 117
Rutas por clasificar: 3468
1524910397
Las opciones para el origen de la ruta 15

Las opciones para el origen de la ruta 1402710397 son: ['PBI']
Aeropuertos clasificados: 122
Rutas por clasificar: 3424
1324413232
Las opciones para el origen de la ruta 1324413232 son: ['MEM']
Aeropuertos clasificados: 123
Rutas por clasificar: 3422
1126710821
Las opciones para el origen de la ruta 1126710821 son: ['JAC', 'DAY']
Las posibilidades encontradas para el origen de la ruta alternativa 1126710397 son: ['DAY']
Las coincidencias encontradas para el origen en la ruta alternativa 1126710397 son: ['DAY']
Las posibilidades encontradas para el origen de la ruta alternativa 1126713930 son: ['DAY', 'ECP']
Las coincidencias encontradas para el origen en la ruta alternativa 1126713930 son: ['DAY']
La ruta alternativa final es: 1126713930
Aeropuertos clasificados: 124
Rutas por clasificar: 3422
1126710821
Aeropuertos clasificados: 124
Rutas por clasificar: 3420
{'14747': 'SEA', '11298': 'DFW', '14831': 'SJC', '14771': 'SFO', '13487': 'MSP', '12889': 'LAS', '12892': 'LAX', '12264': 'IAD'

Las opciones para el origen de la ruta 1294513930 son: ['LEX', 'AMA']
Las posibilidades encontradas para el origen de la ruta alternativa 1294510397 son: ['LIT', 'CEC', 'LEX']
Las coincidencias encontradas para el origen en la ruta alternativa 1294510397 son: ['LEX']
Las posibilidades encontradas para el origen de la ruta alternativa 1294511433 son: ['LIT', 'BUR', 'LEX']
Las coincidencias encontradas para el origen en la ruta alternativa 1294511433 son: ['LEX']
La ruta alternativa final es: 1294511433
Aeropuertos clasificados: 131
Rutas por clasificar: 3378
1294513930
Aeropuertos clasificados: 131
Rutas por clasificar: 3376
1560710397
Las opciones para el origen de la ruta 1560710397 son: ['VLD']
Aeropuertos clasificados: 132
Rutas por clasificar: 3374
1161811697
Aeropuertos clasificados: 132
Rutas por clasificar: 3372
1129811292
Aeropuertos clasificados: 132
Rutas por clasificar: 3370
1106615304
Aeropuertos clasificados: 132
Rutas por clasificar: 3368
1319810821
Aeropuertos clasificad

Las opciones para el origen de la ruta 1087410397 son: ['CAK', 'SCE']
Las posibilidades encontradas para el origen de la ruta alternativa 1087412953 son: ['DLH', 'CAK']
Las coincidencias encontradas para el origen en la ruta alternativa 1087412953 son: ['CAK']
Las posibilidades encontradas para el origen de la ruta alternativa 1087413930 son: ['CAK']
Las coincidencias encontradas para el origen en la ruta alternativa 1087413930 son: ['CAK']
La ruta alternativa final es: 1087413930
Aeropuertos clasificados: 140
Rutas por clasificar: 3318
1087410397
Aeropuertos clasificados: 140
Rutas por clasificar: 3316
1106613796
Aeropuertos clasificados: 140
Rutas por clasificar: 3314
1219113495
Aeropuertos clasificados: 140
Rutas por clasificar: 3312
1288912892
Aeropuertos clasificados: 140
Rutas por clasificar: 3310
1289214831
Aeropuertos clasificados: 140
Rutas por clasificar: 3308
1052913232
Aeropuertos clasificados: 140
Rutas por clasificar: 3306
1059912191
Aeropuertos clasificados: 140
Rutas po

Las opciones para el origen de la ruta 1219710397 son: ['HPN', 'MMH']
Las posibilidades encontradas para el origen de la ruta alternativa 1219711697 son: ['HPN']
Las coincidencias encontradas para el origen en la ruta alternativa 1219711697 son: ['HPN']
Las posibilidades encontradas para el origen de la ruta alternativa 1219713930 son: ['HPN']
Las coincidencias encontradas para el origen en la ruta alternativa 1219713930 son: ['HPN']
La ruta alternativa final es: 1219713930
Aeropuertos clasificados: 146
Rutas por clasificar: 3226
1219710397
Aeropuertos clasificados: 146
Rutas por clasificar: 3224
1409810397
Las opciones para el origen de la ruta 1409810397 son: ['PHF', 'RAP', 'FWA']
No existen más rutas alternativas para este path 1409810397
1232310397
Las opciones para el origen de la ruta 1232310397 son: ['ILM']
Aeropuertos clasificados: 147
Rutas por clasificar: 3222
1057711433
Las opciones para el origen de la ruta 1057711433 son: ['BGM', 'BGR']
No existen más rutas alternativas pa

Las opciones para el origen de la ruta 1535613204 son: ['TTN']
Aeropuertos clasificados: 155
Rutas por clasificar: 3186
1071312892
Aeropuertos clasificados: 155
Rutas por clasificar: 3184
1043113930
Aeropuertos clasificados: 155
Rutas por clasificar: 3182
1410014771
Aeropuertos clasificados: 155
Rutas por clasificar: 3180
{'14747': 'SEA', '11298': 'DFW', '14831': 'SJC', '14771': 'SFO', '13487': 'MSP', '12889': 'LAS', '12892': 'LAX', '12264': 'IAD', '13303': 'MIA', '11057': 'CLT', '13930': 'ORD', '14869': 'SLC', '10693': 'BNA', '10299': 'ANC', '12266': 'IAH', '11292': 'DEN', '12478': 'JFK', '14107': 'PHX', '14057': 'PDX', '10397': 'ATL', '13198': 'MCI', '11630': 'FAI', '12173': 'HNL', '10732': 'BQN', '11618': 'EWR', '14254': 'PSE', '13204': 'MCO', '10627': 'BIS', '11982': 'GRK', '12402': 'ITO', '14683': 'SAT', '10721': 'BOS', '11884': 'GEG', '15919': 'XNA', '13851': 'OKC', '11111': 'COU', '12191': 'HOU', '14783': 'SGF', '15016': 'STL', '12758': 'KOA', '13830': 'OGG', '10423': 'AUS', '15

Las opciones para el origen de la ruta 1027911259 son: ['AMA']
Aeropuertos clasificados: 156
Rutas por clasificar: 3124
1042310397
Aeropuertos clasificados: 156
Rutas por clasificar: 3122
1042311259
Aeropuertos clasificados: 156
Rutas por clasificar: 3120
{'14747': 'SEA', '11298': 'DFW', '14831': 'SJC', '14771': 'SFO', '13487': 'MSP', '12889': 'LAS', '12892': 'LAX', '12264': 'IAD', '13303': 'MIA', '11057': 'CLT', '13930': 'ORD', '14869': 'SLC', '10693': 'BNA', '10299': 'ANC', '12266': 'IAH', '11292': 'DEN', '12478': 'JFK', '14107': 'PHX', '14057': 'PDX', '10397': 'ATL', '13198': 'MCI', '11630': 'FAI', '12173': 'HNL', '10732': 'BQN', '11618': 'EWR', '14254': 'PSE', '13204': 'MCO', '10627': 'BIS', '11982': 'GRK', '12402': 'ITO', '14683': 'SAT', '10721': 'BOS', '11884': 'GEG', '15919': 'XNA', '13851': 'OKC', '11111': 'COU', '12191': 'HOU', '14783': 'SGF', '15016': 'STL', '12758': 'KOA', '13830': 'OGG', '10423': 'AUS', '15370': 'TUL', '11953': 'GNV', '13891': 'ONT', '15376': 'TUS', '11778'

Las opciones para el origen de la ruta 1432110821 son: ['PWM']
Aeropuertos clasificados: 158
Rutas por clasificar: 3078
1474714908
Aeropuertos clasificados: 158
Rutas por clasificar: 3076
1484313204
Aeropuertos clasificados: 158
Rutas por clasificar: 3074
1288913303
Aeropuertos clasificados: 158
Rutas por clasificar: 3072
1072112892
Aeropuertos clasificados: 158
Rutas por clasificar: 3070
1501611298
Aeropuertos clasificados: 158
Rutas por clasificar: 3068
1349513303
Aeropuertos clasificados: 158
Rutas por clasificar: 3066
1484313303
Aeropuertos clasificados: 158
Rutas por clasificar: 3064
1127813303
Aeropuertos clasificados: 158
Rutas por clasificar: 3062
1295311298
Aeropuertos clasificados: 158
Rutas por clasificar: 3060
{'14747': 'SEA', '11298': 'DFW', '14831': 'SJC', '14771': 'SFO', '13487': 'MSP', '12889': 'LAS', '12892': 'LAX', '12264': 'IAD', '13303': 'MIA', '11057': 'CLT', '13930': 'ORD', '14869': 'SLC', '10693': 'BNA', '10299': 'ANC', '12266': 'IAH', '11292': 'DEN', '12478': 'J

Las opciones para el origen de la ruta 1482812523 son: ['JNU', 'SIT']
Las posibilidades encontradas para el origen de la ruta alternativa 1482812819 son: ['SIT', 'KTN', 'OTZ', 'OME']
Las coincidencias encontradas para el origen en la ruta alternativa 1482812819 son: ['SIT']
La ruta alternativa final es: 1482812819
Aeropuertos clasificados: 161
Rutas por clasificar: 3016
1474713796
Aeropuertos clasificados: 161
Rutas por clasificar: 3014
1489314747
Aeropuertos clasificados: 161
Rutas por clasificar: 3012
1509612478
Aeropuertos clasificados: 161
Rutas por clasificar: 3010
1457612478
Aeropuertos clasificados: 161
Rutas por clasificar: 3008
1127811697
Aeropuertos clasificados: 161
Rutas por clasificar: 3006
1432112478
Aeropuertos clasificados: 161
Rutas por clasificar: 3004
1320412478
Aeropuertos clasificados: 161
Rutas por clasificar: 3002
1477112954
Las opciones para el destino de la ruta 1477112954 son: ['LGB']
Aeropuertos clasificados: 162
Rutas por clasificar: 3000
{'14747': 'SEA', '1

Las opciones para el origen de la ruta 1425214869 son: ['PSC']
Aeropuertos clasificados: 169
Rutas por clasificar: 2958
1052910397
Aeropuertos clasificados: 169
Rutas por clasificar: 2956
1062013487
Aeropuertos clasificados: 169
Rutas por clasificar: 2954
1029913487
Aeropuertos clasificados: 169
Rutas por clasificar: 2952
1119310397
Las opciones para el origen de la ruta 1119310397 son: ['CVG']
Aeropuertos clasificados: 170
Rutas por clasificar: 2950
1501610397
Aeropuertos clasificados: 170
Rutas por clasificar: 2948
1084913487
Las opciones para el origen de la ruta 1084913487 son: ['BZN']
Aeropuertos clasificados: 171
Rutas por clasificar: 2946
1419310397
Las opciones para el origen de la ruta 1419310397 son: ['PNS']
Aeropuertos clasificados: 172
Rutas por clasificar: 2944
1498610397
Las opciones para el origen de la ruta 1498610397 son: ['SRQ']
Aeropuertos clasificados: 173
Rutas por clasificar: 2942
1195310397
Aeropuertos clasificados: 173
Rutas por clasificar: 2940
{'14747': 'SEA',

Las opciones para el origen de la ruta 1182311298 son: ['FWA']
Aeropuertos clasificados: 178
Rutas por clasificar: 2892
1198011298
Las opciones para el origen de la ruta 1198011298 son: ['GRI']
Aeropuertos clasificados: 179
Rutas por clasificar: 2890
1233913930
Aeropuertos clasificados: 179
Rutas por clasificar: 2888
1329013930
Las opciones para el origen de la ruta 1329013930 son: ['HOB', 'MHK']
Las posibilidades encontradas para el origen de la ruta alternativa 1329011298 son: ['MHK']
Las coincidencias encontradas para el origen en la ruta alternativa 1329011298 son: ['MHK']
La ruta alternativa final es: 1329011298
Aeropuertos clasificados: 180
Rutas por clasificar: 2888
1329013930
Aeropuertos clasificados: 180
Rutas por clasificar: 2886
1119313303
Aeropuertos clasificados: 180
Rutas por clasificar: 2884
1015815304
Las opciones para el origen de la ruta 1015815304 son: ['ASE', 'ACY']
Las posibilidades encontradas para el origen de la ruta alternativa 1015813577 son: ['ACY']
Las coinc

Las opciones para el origen de la ruta 1454311292 son: ['RKS']
Aeropuertos clasificados: 188
Rutas por clasificar: 2856
1490514771
Las opciones para el origen de la ruta 1490514771 son: ['GJT', 'SMX']
No existen más rutas alternativas para este path 1490514771
1158711433
Las opciones para el origen de la ruta 1158711433 son: ['ESC']
Aeropuertos clasificados: 189
Rutas por clasificar: 2854
1445711292
Las opciones para el origen de la ruta 1445711292 son: ['RAP']
Aeropuertos clasificados: 190
Rutas por clasificar: 2852
1233514520
Las opciones para el origen de la ruta 1233514520 son: ['IMT', 'RHI', 'CWA']
Las posibilidades encontradas para el origen de la ruta alternativa 1233513487 son: ['ABR', 'IMT']
Las coincidencias encontradas para el origen en la ruta alternativa 1233513487 son: ['IMT']
La ruta alternativa final es: 1233513487
Aeropuertos clasificados: 191
Rutas por clasificar: 2852
1233514520
Las opciones para el destino de la ruta 1233514520 son: ['RHI', 'CWA']
Las posibilidades 

Las opciones para el origen de la ruta 1026813930 son: ['ALO', 'KTN']
No existen más rutas alternativas para este path 1026813930
1119313930
Aeropuertos clasificados: 198
Rutas por clasificar: 2746
1529513930
Las opciones para el origen de la ruta 1529513930 son: ['TOL', 'YAK', 'CDV', 'CWA']
No existen más rutas alternativas para este path 1529513930
1163814747
Aeropuertos clasificados: 198
Rutas por clasificar: 2744
1238911292
Las opciones para el origen de la ruta 1238911292 son: ['ISN']
Aeropuertos clasificados: 199
Rutas por clasificar: 2742
1152514869
Las opciones para el origen de la ruta 1152514869 son: ['EKO']
Aeropuertos clasificados: 200
Rutas por clasificar: 2740
{'14747': 'SEA', '11298': 'DFW', '14831': 'SJC', '14771': 'SFO', '13487': 'MSP', '12889': 'LAS', '12892': 'LAX', '12264': 'IAD', '13303': 'MIA', '11057': 'CLT', '13930': 'ORD', '14869': 'SLC', '10693': 'BNA', '10299': 'ANC', '12266': 'IAH', '11292': 'DEN', '12478': 'JFK', '14107': 'PHX', '14057': 'PDX', '10397': 'AT

Las opciones para el origen de la ruta 1239110821 son: ['ISP']
Aeropuertos clasificados: 202
Rutas por clasificar: 2706
1289213198
Aeropuertos clasificados: 202
Rutas por clasificar: 2704
1349512889
Aeropuertos clasificados: 202
Rutas por clasificar: 2702
1379612191
Aeropuertos clasificados: 202
Rutas por clasificar: 2700
{'14747': 'SEA', '11298': 'DFW', '14831': 'SJC', '14771': 'SFO', '13487': 'MSP', '12889': 'LAS', '12892': 'LAX', '12264': 'IAD', '13303': 'MIA', '11057': 'CLT', '13930': 'ORD', '14869': 'SLC', '10693': 'BNA', '10299': 'ANC', '12266': 'IAH', '11292': 'DEN', '12478': 'JFK', '14107': 'PHX', '14057': 'PDX', '10397': 'ATL', '13198': 'MCI', '11630': 'FAI', '12173': 'HNL', '10732': 'BQN', '11618': 'EWR', '14254': 'PSE', '13204': 'MCO', '10627': 'BIS', '11982': 'GRK', '12402': 'ITO', '14683': 'SAT', '10721': 'BOS', '11884': 'GEG', '15919': 'XNA', '13851': 'OKC', '11111': 'COU', '12191': 'HOU', '14783': 'SGF', '15016': 'STL', '12758': 'KOA', '13830': 'OGG', '10423': 'AUS', '15

Las opciones para el origen de la ruta 1469610397 son: ['ELM', 'SBN']
Las posibilidades encontradas para el origen de la ruta alternativa 1469611433 son: ['SBN', 'TYS']
Las coincidencias encontradas para el origen en la ruta alternativa 1469611433 son: ['SBN']
La ruta alternativa final es: 1469611433
Aeropuertos clasificados: 204
Rutas por clasificar: 2660
{'14747': 'SEA', '11298': 'DFW', '14831': 'SJC', '14771': 'SFO', '13487': 'MSP', '12889': 'LAS', '12892': 'LAX', '12264': 'IAD', '13303': 'MIA', '11057': 'CLT', '13930': 'ORD', '14869': 'SLC', '10693': 'BNA', '10299': 'ANC', '12266': 'IAH', '11292': 'DEN', '12478': 'JFK', '14107': 'PHX', '14057': 'PDX', '10397': 'ATL', '13198': 'MCI', '11630': 'FAI', '12173': 'HNL', '10732': 'BQN', '11618': 'EWR', '14254': 'PSE', '13204': 'MCO', '10627': 'BIS', '11982': 'GRK', '12402': 'ITO', '14683': 'SAT', '10721': 'BOS', '11884': 'GEG', '15919': 'XNA', '13851': 'OKC', '11111': 'COU', '12191': 'HOU', '14783': 'SGF', '15016': 'STL', '12758': 'KOA', 

Las opciones para el origen de la ruta 1073110397 son: ['BQK']
Aeropuertos clasificados: 207
Rutas por clasificar: 2624
1468312266
Aeropuertos clasificados: 207
Rutas por clasificar: 2622
1467911618
Aeropuertos clasificados: 207
Rutas por clasificar: 2620
{'14747': 'SEA', '11298': 'DFW', '14831': 'SJC', '14771': 'SFO', '13487': 'MSP', '12889': 'LAS', '12892': 'LAX', '12264': 'IAD', '13303': 'MIA', '11057': 'CLT', '13930': 'ORD', '14869': 'SLC', '10693': 'BNA', '10299': 'ANC', '12266': 'IAH', '11292': 'DEN', '12478': 'JFK', '14107': 'PHX', '14057': 'PDX', '10397': 'ATL', '13198': 'MCI', '11630': 'FAI', '12173': 'HNL', '10732': 'BQN', '11618': 'EWR', '14254': 'PSE', '13204': 'MCO', '10627': 'BIS', '11982': 'GRK', '12402': 'ITO', '14683': 'SAT', '10721': 'BOS', '11884': 'GEG', '15919': 'XNA', '13851': 'OKC', '11111': 'COU', '12191': 'HOU', '14783': 'SGF', '15016': 'STL', '12758': 'KOA', '13830': 'OGG', '10423': 'AUS', '15370': 'TUL', '11953': 'GNV', '13891': 'ONT', '15376': 'TUS', '11778'

Las opciones para el origen de la ruta 1141311298 son: ['DRO']
Aeropuertos clasificados: 209
Rutas por clasificar: 2548
1082113930
Aeropuertos clasificados: 209
Rutas por clasificar: 2546
1347614107
Aeropuertos clasificados: 209
Rutas por clasificar: 2544
1448914771
Aeropuertos clasificados: 209
Rutas por clasificar: 2542
1200314869
Aeropuertos clasificados: 209
Rutas por clasificar: 2540
{'14747': 'SEA', '11298': 'DFW', '14831': 'SJC', '14771': 'SFO', '13487': 'MSP', '12889': 'LAS', '12892': 'LAX', '12264': 'IAD', '13303': 'MIA', '11057': 'CLT', '13930': 'ORD', '14869': 'SLC', '10693': 'BNA', '10299': 'ANC', '12266': 'IAH', '11292': 'DEN', '12478': 'JFK', '14107': 'PHX', '14057': 'PDX', '10397': 'ATL', '13198': 'MCI', '11630': 'FAI', '12173': 'HNL', '10732': 'BQN', '11618': 'EWR', '14254': 'PSE', '13204': 'MCO', '10627': 'BIS', '11982': 'GRK', '12402': 'ITO', '14683': 'SAT', '10721': 'BOS', '11884': 'GEG', '15919': 'XNA', '13851': 'OKC', '11111': 'COU', '12191': 'HOU', '14783': 'SGF',

Las opciones para el origen de la ruta 1186711298 son: ['GCK']
Aeropuertos clasificados: 211
Rutas por clasificar: 2468
1069312953
Aeropuertos clasificados: 211
Rutas por clasificar: 2466
1018511298
Aeropuertos clasificados: 211
Rutas por clasificar: 2464
1329011298
Aeropuertos clasificados: 211
Rutas por clasificar: 2462
1141314107
Aeropuertos clasificados: 211
Rutas por clasificar: 2460
{'14747': 'SEA', '11298': 'DFW', '14831': 'SJC', '14771': 'SFO', '13487': 'MSP', '12889': 'LAS', '12892': 'LAX', '12264': 'IAD', '13303': 'MIA', '11057': 'CLT', '13930': 'ORD', '14869': 'SLC', '10693': 'BNA', '10299': 'ANC', '12266': 'IAH', '11292': 'DEN', '12478': 'JFK', '14107': 'PHX', '14057': 'PDX', '10397': 'ATL', '13198': 'MCI', '11630': 'FAI', '12173': 'HNL', '10732': 'BQN', '11618': 'EWR', '14254': 'PSE', '13204': 'MCO', '10627': 'BIS', '11982': 'GRK', '12402': 'ITO', '14683': 'SAT', '10721': 'BOS', '11884': 'GEG', '15919': 'XNA', '13851': 'OKC', '11111': 'COU', '12191': 'HOU', '14783': 'SGF',

Las opciones para el origen de la ruta 1133713930 son: ['DLH']
Aeropuertos clasificados: 214
Rutas por clasificar: 2432
1385114869
Aeropuertos clasificados: 214
Rutas por clasificar: 2430
1294511298
Aeropuertos clasificados: 214
Rutas por clasificar: 2428
1591912266
Aeropuertos clasificados: 214
Rutas por clasificar: 2426
1059912953
Aeropuertos clasificados: 214
Rutas por clasificar: 2424
1319812953
Aeropuertos clasificados: 214
Rutas por clasificar: 2422
1393010423
Aeropuertos clasificados: 214
Rutas por clasificar: 2420
{'14747': 'SEA', '11298': 'DFW', '14831': 'SJC', '14771': 'SFO', '13487': 'MSP', '12889': 'LAS', '12892': 'LAX', '12264': 'IAD', '13303': 'MIA', '11057': 'CLT', '13930': 'ORD', '14869': 'SLC', '10693': 'BNA', '10299': 'ANC', '12266': 'IAH', '11292': 'DEN', '12478': 'JFK', '14107': 'PHX', '14057': 'PDX', '10397': 'ATL', '13198': 'MCI', '11630': 'FAI', '12173': 'HNL', '10732': 'BQN', '11618': 'EWR', '14254': 'PSE', '13204': 'MCO', '10627': 'BIS', '11982': 'GRK', '12402'

Las opciones para el origen de la ruta 1336010397 son: ['MLB']
Aeropuertos clasificados: 215
Rutas por clasificar: 2382
1197310397
Aeropuertos clasificados: 215
Rutas por clasificar: 2380
{'14747': 'SEA', '11298': 'DFW', '14831': 'SJC', '14771': 'SFO', '13487': 'MSP', '12889': 'LAS', '12892': 'LAX', '12264': 'IAD', '13303': 'MIA', '11057': 'CLT', '13930': 'ORD', '14869': 'SLC', '10693': 'BNA', '10299': 'ANC', '12266': 'IAH', '11292': 'DEN', '12478': 'JFK', '14107': 'PHX', '14057': 'PDX', '10397': 'ATL', '13198': 'MCI', '11630': 'FAI', '12173': 'HNL', '10732': 'BQN', '11618': 'EWR', '14254': 'PSE', '13204': 'MCO', '10627': 'BIS', '11982': 'GRK', '12402': 'ITO', '14683': 'SAT', '10721': 'BOS', '11884': 'GEG', '15919': 'XNA', '13851': 'OKC', '11111': 'COU', '12191': 'HOU', '14783': 'SGF', '15016': 'STL', '12758': 'KOA', '13830': 'OGG', '10423': 'AUS', '15370': 'TUL', '11953': 'GNV', '13891': 'ONT', '15376': 'TUS', '11778': 'FSM', '11278': 'DCA', '14100': 'PHL', '15304': 'TPA', '11637': 'F

Las opciones para el origen de la ruta 1540111298 son: ['TXK']
Aeropuertos clasificados: 219
Rutas por clasificar: 2350
1127813487
Aeropuertos clasificados: 219
Rutas por clasificar: 2348
1323010397
Las opciones para el origen de la ruta 1323010397 son: ['MDT']
Aeropuertos clasificados: 220
Rutas por clasificar: 2346
1320411433
Aeropuertos clasificados: 220
Rutas por clasificar: 2344
1468512266
Aeropuertos clasificados: 220
Rutas por clasificar: 2342
1342212266
Aeropuertos clasificados: 220
Rutas por clasificar: 2340
{'14747': 'SEA', '11298': 'DFW', '14831': 'SJC', '14771': 'SFO', '13487': 'MSP', '12889': 'LAS', '12892': 'LAX', '12264': 'IAD', '13303': 'MIA', '11057': 'CLT', '13930': 'ORD', '14869': 'SLC', '10693': 'BNA', '10299': 'ANC', '12266': 'IAH', '11292': 'DEN', '12478': 'JFK', '14107': 'PHX', '14057': 'PDX', '10397': 'ATL', '13198': 'MCI', '11630': 'FAI', '12173': 'HNL', '10732': 'BQN', '11618': 'EWR', '14254': 'PSE', '13204': 'MCO', '10627': 'BIS', '11982': 'GRK', '12402': 'IT

Las opciones para el origen de la ruta 1106713930 son: ['CMI']
Aeropuertos clasificados: 222
Rutas por clasificar: 2254
1291511298
Aeropuertos clasificados: 222
Rutas por clasificar: 2252
1068513930
Aeropuertos clasificados: 222
Rutas por clasificar: 2250
1127413930
Las opciones para el origen de la ruta 1127413930 son: ['DBQ']
Aeropuertos clasificados: 223
Rutas por clasificar: 2248
1192111298
Las opciones para el origen de la ruta 1192111298 son: ['GJT']
Aeropuertos clasificados: 224
Rutas por clasificar: 2246
1591912953
Aeropuertos clasificados: 224
Rutas por clasificar: 2244
1182313930
Aeropuertos clasificados: 224
Rutas por clasificar: 2242
1056114107
Aeropuertos clasificados: 224
Rutas por clasificar: 2240
{'14747': 'SEA', '11298': 'DFW', '14831': 'SJC', '14771': 'SFO', '13487': 'MSP', '12889': 'LAS', '12892': 'LAX', '12264': 'IAD', '13303': 'MIA', '11057': 'CLT', '13930': 'ORD', '14869': 'SLC', '10693': 'BNA', '10299': 'ANC', '12266': 'IAH', '11292': 'DEN', '12478': 'JFK', '1410

Las opciones para el destino de la ruta 1029913970 son: ['OTZ']
Aeropuertos clasificados: 225
Rutas por clasificar: 2152
1219711697
Aeropuertos clasificados: 225
Rutas por clasificar: 2150
1072113204
Aeropuertos clasificados: 225
Rutas por clasificar: 2148
1079211433
Aeropuertos clasificados: 225
Rutas por clasificar: 2146
1062711298
Aeropuertos clasificados: 225
Rutas por clasificar: 2144
1077914869
Las opciones para el origen de la ruta 1077914869 son: ['BTM']
Aeropuertos clasificados: 226
Rutas por clasificar: 2142
1415011433
Las opciones para el origen de la ruta 1415011433 son: ['PLN']
Aeropuertos clasificados: 227
Rutas por clasificar: 2140
{'14747': 'SEA', '11298': 'DFW', '14831': 'SJC', '14771': 'SFO', '13487': 'MSP', '12889': 'LAS', '12892': 'LAX', '12264': 'IAD', '13303': 'MIA', '11057': 'CLT', '13930': 'ORD', '14869': 'SLC', '10693': 'BNA', '10299': 'ANC', '12266': 'IAH', '11292': 'DEN', '12478': 'JFK', '14107': 'PHX', '14057': 'PDX', '10397': 'ATL', '13198': 'MCI', '11630':

Las opciones para el destino de la ruta 1393013184 son: ['SUN', 'MBS']
Las posibilidades encontradas para el destino en la ruta alternativa 1318413487 son: ['MBS']
Las coincidencias encontradas para el destino en la ruta alternativa 1318413487 son: ['MBS']
La ruta alternativa final es: 1318413487
Aeropuertos clasificados: 231
Rutas por clasificar: 2070
1172113487
Aeropuertos clasificados: 231
Rutas por clasificar: 2068
1490810397
Aeropuertos clasificados: 231
Rutas por clasificar: 2066
1541212266
Aeropuertos clasificados: 231
Rutas por clasificar: 2064
1161211433
Aeropuertos clasificados: 231
Rutas por clasificar: 2062
1200710397
Las opciones para el origen de la ruta 1200710397 son: ['GTR']
Aeropuertos clasificados: 232
Rutas por clasificar: 2060
{'14747': 'SEA', '11298': 'DFW', '14831': 'SJC', '14771': 'SFO', '13487': 'MSP', '12889': 'LAS', '12892': 'LAX', '12264': 'IAD', '13303': 'MIA', '11057': 'CLT', '13930': 'ORD', '14869': 'SLC', '10693': 'BNA', '10299': 'ANC', '12266': 'IAH', '

Las opciones para el origen de la ruta 1458811298 son: ['ROW']
Aeropuertos clasificados: 233
Rutas por clasificar: 2020
{'14747': 'SEA', '11298': 'DFW', '14831': 'SJC', '14771': 'SFO', '13487': 'MSP', '12889': 'LAS', '12892': 'LAX', '12264': 'IAD', '13303': 'MIA', '11057': 'CLT', '13930': 'ORD', '14869': 'SLC', '10693': 'BNA', '10299': 'ANC', '12266': 'IAH', '11292': 'DEN', '12478': 'JFK', '14107': 'PHX', '14057': 'PDX', '10397': 'ATL', '13198': 'MCI', '11630': 'FAI', '12173': 'HNL', '10732': 'BQN', '11618': 'EWR', '14254': 'PSE', '13204': 'MCO', '10627': 'BIS', '11982': 'GRK', '12402': 'ITO', '14683': 'SAT', '10721': 'BOS', '11884': 'GEG', '15919': 'XNA', '13851': 'OKC', '11111': 'COU', '12191': 'HOU', '14783': 'SGF', '15016': 'STL', '12758': 'KOA', '13830': 'OGG', '10423': 'AUS', '15370': 'TUL', '11953': 'GNV', '13891': 'ONT', '15376': 'TUS', '11778': 'FSM', '11278': 'DCA', '14100': 'PHL', '15304': 'TPA', '11637': 'FAR', '11775': 'FSD', '12982': 'LIH', '13931': 'ORF', '10821': 'BWI',

Las opciones para el origen de la ruta 1306112266 son: ['SCE', 'LRD']
Las posibilidades encontradas para el origen de la ruta alternativa 1306111298 son: ['LRD']
Las coincidencias encontradas para el origen en la ruta alternativa 1306111298 son: ['LRD']
La ruta alternativa final es: 1306111298
Aeropuertos clasificados: 234
Rutas por clasificar: 1980
{'14747': 'SEA', '11298': 'DFW', '14831': 'SJC', '14771': 'SFO', '13487': 'MSP', '12889': 'LAS', '12892': 'LAX', '12264': 'IAD', '13303': 'MIA', '11057': 'CLT', '13930': 'ORD', '14869': 'SLC', '10693': 'BNA', '10299': 'ANC', '12266': 'IAH', '11292': 'DEN', '12478': 'JFK', '14107': 'PHX', '14057': 'PDX', '10397': 'ATL', '13198': 'MCI', '11630': 'FAI', '12173': 'HNL', '10732': 'BQN', '11618': 'EWR', '14254': 'PSE', '13204': 'MCO', '10627': 'BIS', '11982': 'GRK', '12402': 'ITO', '14683': 'SAT', '10721': 'BOS', '11884': 'GEG', '15919': 'XNA', '13851': 'OKC', '11111': 'COU', '12191': 'HOU', '14783': 'SGF', '15016': 'STL', '12758': 'KOA', '13830'

Las opciones para el destino de la ruta 1393014574 son: ['ROA']
Aeropuertos clasificados: 236
Rutas por clasificar: 1912
1042311057
Aeropuertos clasificados: 236
Rutas por clasificar: 1910
1410913241
Las opciones para el origen de la ruta 1410913241 son: ['PIB', 'MEI']
Las posibilidades encontradas para el origen de la ruta alternativa 1410911298 son: ['PIB']
Las coincidencias encontradas para el origen en la ruta alternativa 1410911298 son: ['PIB']
La ruta alternativa final es: 1410911298
Aeropuertos clasificados: 238
Rutas por clasificar: 1908
1393011433
Aeropuertos clasificados: 238
Rutas por clasificar: 1906
1405713487
Aeropuertos clasificados: 238
Rutas por clasificar: 1904
1129812217
Aeropuertos clasificados: 238
Rutas por clasificar: 1902
1199613930
Aeropuertos clasificados: 238
Rutas por clasificar: 1900
{'14747': 'SEA', '11298': 'DFW', '14831': 'SJC', '14771': 'SFO', '13487': 'MSP', '12889': 'LAS', '12892': 'LAX', '12264': 'IAD', '13303': 'MIA', '11057': 'CLT', '13930': 'ORD',

Las opciones para el origen de la ruta 1244114869 son: ['JAC']
Aeropuertos clasificados: 239
Rutas por clasificar: 1760
{'14747': 'SEA', '11298': 'DFW', '14831': 'SJC', '14771': 'SFO', '13487': 'MSP', '12889': 'LAS', '12892': 'LAX', '12264': 'IAD', '13303': 'MIA', '11057': 'CLT', '13930': 'ORD', '14869': 'SLC', '10693': 'BNA', '10299': 'ANC', '12266': 'IAH', '11292': 'DEN', '12478': 'JFK', '14107': 'PHX', '14057': 'PDX', '10397': 'ATL', '13198': 'MCI', '11630': 'FAI', '12173': 'HNL', '10732': 'BQN', '11618': 'EWR', '14254': 'PSE', '13204': 'MCO', '10627': 'BIS', '11982': 'GRK', '12402': 'ITO', '14683': 'SAT', '10721': 'BOS', '11884': 'GEG', '15919': 'XNA', '13851': 'OKC', '11111': 'COU', '12191': 'HOU', '14783': 'SGF', '15016': 'STL', '12758': 'KOA', '13830': 'OGG', '10423': 'AUS', '15370': 'TUL', '11953': 'GNV', '13891': 'ONT', '15376': 'TUS', '11778': 'FSM', '11278': 'DCA', '14100': 'PHL', '15304': 'TPA', '11637': 'FAR', '11775': 'FSD', '12982': 'LIH', '13931': 'ORF', '10821': 'BWI',

Las opciones para el origen de la ruta 1073913487 son: ['BRD']
Aeropuertos clasificados: 245
Rutas por clasificar: 1647
1426212892
Aeropuertos clasificados: 245
Rutas por clasificar: 1645
1307613487
Aeropuertos clasificados: 245
Rutas por clasificar: 1643
1490814869
Aeropuertos clasificados: 245
Rutas por clasificar: 1641
1163814771
Aeropuertos clasificados: 245
Rutas por clasificar: 1639
1471113930
Las opciones para el origen de la ruta 1471113930 son: ['SCE']
Aeropuertos clasificados: 246
Rutas por clasificar: 1637
1348713198
Aeropuertos clasificados: 246
Rutas por clasificar: 1635
1348711986
Aeropuertos clasificados: 246
Rutas por clasificar: 1633
1457613930
Aeropuertos clasificados: 246
Rutas por clasificar: 1631
1127810529
Aeropuertos clasificados: 246
Rutas por clasificar: 1629
1467911433
Aeropuertos clasificados: 246
Rutas por clasificar: 1627
1289612266
Aeropuertos clasificados: 246
Rutas por clasificar: 1625
1320414771
Aeropuertos clasificados: 246
Rutas por clasificar: 1623
1

Las opciones para el destino de la ruta 1484315024 son: ['STT']
Aeropuertos clasificados: 250
Rutas por clasificar: 1409
1099411278
Aeropuertos clasificados: 250
Rutas por clasificar: 1407
1405712954
Aeropuertos clasificados: 250
Rutas por clasificar: 1405
1486911433
Aeropuertos clasificados: 250
Rutas por clasificar: 1403
1349514869
Aeropuertos clasificados: 250
Rutas por clasificar: 1401
1348711066
Aeropuertos clasificados: 250
Rutas por clasificar: 1399
1082114869
Aeropuertos clasificados: 250
Rutas por clasificar: 1397
1537614771
Aeropuertos clasificados: 250
Rutas por clasificar: 1395
1228014869
Las opciones para el origen de la ruta 1228014869 son: ['IDA']
Aeropuertos clasificados: 251
Rutas por clasificar: 1393
1501614771
Aeropuertos clasificados: 251
Rutas por clasificar: 1391
1069314869
Aeropuertos clasificados: 251
Rutas por clasificar: 1389
1182313487
Aeropuertos clasificados: 251
Rutas por clasificar: 1387
1469611618
Aeropuertos clasificados: 251
Rutas por clasificar: 1385


Las opciones para el origen de la ruta 1467411298 son: ['SAF']
Aeropuertos clasificados: 254
Rutas por clasificar: 1135
1192114107
Aeropuertos clasificados: 254
Rutas por clasificar: 1133
1127814843
Aeropuertos clasificados: 254
Rutas por clasificar: 1131
1468312478
Aeropuertos clasificados: 254
Rutas por clasificar: 1129
1477111278
Aeropuertos clasificados: 254
Rutas por clasificar: 1127
1288910279
Aeropuertos clasificados: 254
Rutas por clasificar: 1125
1319813204
Aeropuertos clasificados: 254
Rutas por clasificar: 1123
1320413495
Aeropuertos clasificados: 254
Rutas por clasificar: 1121
1323213851
Aeropuertos clasificados: 254
Rutas por clasificar: 1119
1323214869
Aeropuertos clasificados: 254
Rutas por clasificar: 1117
1477110157
Las opciones para el destino de la ruta 1477110157 son: ['ACV']
Aeropuertos clasificados: 255
Rutas por clasificar: 1115
1457611057
Aeropuertos clasificados: 255
Rutas por clasificar: 1113
1106612953
Aeropuertos clasificados: 255
Rutas por clasificar: 1111


Las opciones para el destino de la ruta 1039713795 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1039713795
1275813830
Aeropuertos clasificados: 263
Rutas por clasificar: 907
1334213198
Aeropuertos clasificados: 263
Rutas por clasificar: 905
1226610140
Aeropuertos clasificados: 263
Rutas por clasificar: 903
1348714683
Aeropuertos clasificados: 263
Rutas por clasificar: 901
1393013344
Las opciones para el destino de la ruta 1393013344 son: ['MKG']
Aeropuertos clasificados: 264
Rutas por clasificar: 899
1100311292
Aeropuertos clasificados: 264
Rutas por clasificar: 897
1106611292
Aeropuertos clasificados: 264
Rutas por clasificar: 895
1161812173
Aeropuertos clasificados: 264
Rutas por clasificar: 893
1393012173
Aeropuertos clasificados: 264
Rutas por clasificar: 891
1233912191
Aeropuertos clasificados: 264
Rutas por clasificar: 889
1288914492
Aeropuertos clasificados: 264
Rutas por clasificar: 887
1501615304
Aeropuertos clasificados: 264
Rutas por clasificar: 885
1

Las opciones para el destino de la ruta 1281915841 son: ['WRG']
Aeropuertos clasificados: 265
Rutas por clasificar: 796
1039715024
Aeropuertos clasificados: 265
Rutas por clasificar: 794
1227811292
Aeropuertos clasificados: 265
Rutas por clasificar: 792
1245110693
Aeropuertos clasificados: 265
Rutas por clasificar: 790
1299214107
Aeropuertos clasificados: 265
Rutas por clasificar: 788
1148112191
Aeropuertos clasificados: 265
Rutas por clasificar: 786
1410013495
Aeropuertos clasificados: 265
Rutas por clasificar: 784
1410014057
Aeropuertos clasificados: 265
Rutas por clasificar: 782
1039714098
Las opciones para el destino de la ruta 1039714098 son: ['PHF']
Aeropuertos clasificados: 266
Rutas por clasificar: 780
{'14747': 'SEA', '11298': 'DFW', '14831': 'SJC', '14771': 'SFO', '13487': 'MSP', '12889': 'LAS', '12892': 'LAX', '12264': 'IAD', '13303': 'MIA', '11057': 'CLT', '13930': 'ORD', '14869': 'SLC', '10693': 'BNA', '10299': 'ANC', '12266': 'IAH', '11292': 'DEN', '12478': 'JFK', '14107'

Las opciones para el destino de la ruta 1252315991 son: ['BJI', 'RDD', 'YAK', 'ACK']
Las posibilidades encontradas para el destino en la ruta alternativa 1599110926 son: ['TOL', 'YAK', 'CDV', 'CWA']
Las coincidencias encontradas para el destino en la ruta alternativa 1599110926 son: ['YAK']
La ruta alternativa final es: 1599110926
Aeropuertos clasificados: 267
Rutas por clasificar: 756
1486911618
Aeropuertos clasificados: 267
Rutas por clasificar: 754
1348713495
Aeropuertos clasificados: 267
Rutas por clasificar: 752
1129214814
Aeropuertos clasificados: 267
Rutas por clasificar: 750
1143311193
Aeropuertos clasificados: 267
Rutas por clasificar: 748
1106611278
Aeropuertos clasificados: 267
Rutas por clasificar: 746
1473013204
Aeropuertos clasificados: 267
Rutas por clasificar: 744
1474714262
Aeropuertos clasificados: 267
Rutas por clasificar: 742
1405715016
Aeropuertos clasificados: 267
Rutas por clasificar: 740
{'14747': 'SEA', '11298': 'DFW', '14831': 'SJC', '14771': 'SFO', '13487': '

Las opciones para el destino de la ruta 1470910754 son: ['BRW']
Aeropuertos clasificados: 268
Rutas por clasificar: 708
1226611049
Aeropuertos clasificados: 268
Rutas por clasificar: 706
1226614843
Aeropuertos clasificados: 268
Rutas por clasificar: 704
1405710140
Aeropuertos clasificados: 268
Rutas por clasificar: 702
1320413244
Aeropuertos clasificados: 268
Rutas por clasificar: 700
{'14747': 'SEA', '11298': 'DFW', '14831': 'SJC', '14771': 'SFO', '13487': 'MSP', '12889': 'LAS', '12892': 'LAX', '12264': 'IAD', '13303': 'MIA', '11057': 'CLT', '13930': 'ORD', '14869': 'SLC', '10693': 'BNA', '10299': 'ANC', '12266': 'IAH', '11292': 'DEN', '12478': 'JFK', '14107': 'PHX', '14057': 'PDX', '10397': 'ATL', '13198': 'MCI', '11630': 'FAI', '12173': 'HNL', '10732': 'BQN', '11618': 'EWR', '14254': 'PSE', '13204': 'MCO', '10627': 'BIS', '11982': 'GRK', '12402': 'ITO', '14683': 'SAT', '10721': 'BOS', '11884': 'GEG', '15919': 'XNA', '13851': 'OKC', '11111': 'COU', '12191': 'HOU', '14783': 'SGF', '15

Las opciones para el origen de la ruta 1033311433 son: ['APN']
Aeropuertos clasificados: 270
Rutas por clasificar: 660
{'14747': 'SEA', '11298': 'DFW', '14831': 'SJC', '14771': 'SFO', '13487': 'MSP', '12889': 'LAS', '12892': 'LAX', '12264': 'IAD', '13303': 'MIA', '11057': 'CLT', '13930': 'ORD', '14869': 'SLC', '10693': 'BNA', '10299': 'ANC', '12266': 'IAH', '11292': 'DEN', '12478': 'JFK', '14107': 'PHX', '14057': 'PDX', '10397': 'ATL', '13198': 'MCI', '11630': 'FAI', '12173': 'HNL', '10732': 'BQN', '11618': 'EWR', '14254': 'PSE', '13204': 'MCO', '10627': 'BIS', '11982': 'GRK', '12402': 'ITO', '14683': 'SAT', '10721': 'BOS', '11884': 'GEG', '15919': 'XNA', '13851': 'OKC', '11111': 'COU', '12191': 'HOU', '14783': 'SGF', '15016': 'STL', '12758': 'KOA', '13830': 'OGG', '10423': 'AUS', '15370': 'TUL', '11953': 'GNV', '13891': 'ONT', '15376': 'TUS', '11778': 'FSM', '11278': 'DCA', '14100': 'PHL', '15304': 'TPA', '11637': 'FAR', '11775': 'FSD', '12982': 'LIH', '13931': 'ORF', '10821': 'BWI', 

Las opciones para el destino de la ruta 1486913127 son: ['LWS']
Aeropuertos clasificados: 271
Rutas por clasificar: 592
1295410423
Aeropuertos clasificados: 271
Rutas por clasificar: 590
1052915304
Aeropuertos clasificados: 271
Rutas por clasificar: 588
1129212094
Las opciones para el destino de la ruta 1129212094 son: ['HDN']
Aeropuertos clasificados: 272
Rutas por clasificar: 586
1288912896
Aeropuertos clasificados: 272
Rutas por clasificar: 584
1299212889
Aeropuertos clasificados: 272
Rutas por clasificar: 582
1379610423
Aeropuertos clasificados: 272
Rutas por clasificar: 580
{'14747': 'SEA', '11298': 'DFW', '14831': 'SJC', '14771': 'SFO', '13487': 'MSP', '12889': 'LAS', '12892': 'LAX', '12264': 'IAD', '13303': 'MIA', '11057': 'CLT', '13930': 'ORD', '14869': 'SLC', '10693': 'BNA', '10299': 'ANC', '12266': 'IAH', '11292': 'DEN', '12478': 'JFK', '14107': 'PHX', '14057': 'PDX', '10397': 'ATL', '13198': 'MCI', '11630': 'FAI', '12173': 'HNL', '10732': 'BQN', '11618': 'EWR', '14254': 'PSE

Las opciones para el destino de la ruta 1599110926 son: ['TOL', 'CDV', 'CWA']
Las posibilidades encontradas para el destino en la ruta alternativa 1092610299 son: ['YUM', 'CDV']
Las coincidencias encontradas para el destino en la ruta alternativa 1092610299 son: ['CDV']
La ruta alternativa final es: 1092610299
Aeropuertos clasificados: 275
Rutas por clasificar: 520
{'14747': 'SEA', '11298': 'DFW', '14831': 'SJC', '14771': 'SFO', '13487': 'MSP', '12889': 'LAS', '12892': 'LAX', '12264': 'IAD', '13303': 'MIA', '11057': 'CLT', '13930': 'ORD', '14869': 'SLC', '10693': 'BNA', '10299': 'ANC', '12266': 'IAH', '11292': 'DEN', '12478': 'JFK', '14107': 'PHX', '14057': 'PDX', '10397': 'ATL', '13198': 'MCI', '11630': 'FAI', '12173': 'HNL', '10732': 'BQN', '11618': 'EWR', '14254': 'PSE', '13204': 'MCO', '10627': 'BIS', '11982': 'GRK', '12402': 'ITO', '14683': 'SAT', '10721': 'BOS', '11884': 'GEG', '15919': 'XNA', '13851': 'OKC', '11111': 'COU', '12191': 'HOU', '14783': 'SGF', '15016': 'STL', '12758'

Las opciones para el destino de la ruta 1393010268 son: ['ALO']
Aeropuertos clasificados: 280
Rutas por clasificar: 411
1342213930
Aeropuertos clasificados: 280
Rutas por clasificar: 409
1289213851
Aeropuertos clasificados: 280
Rutas por clasificar: 407
1072113495
Aeropuertos clasificados: 280
Rutas por clasificar: 405
1405710849
Aeropuertos clasificados: 280
Rutas por clasificar: 403
1348714633
Aeropuertos clasificados: 280
Rutas por clasificar: 401
1295314986
Aeropuertos clasificados: 280
Rutas por clasificar: 399
1535614492
Aeropuertos clasificados: 280
Rutas por clasificar: 397
1247813541
Las opciones para el destino de la ruta 1247813541 son: ['MVY']
Aeropuertos clasificados: 281
Rutas por clasificar: 395
1486911423
Aeropuertos clasificados: 281
Rutas por clasificar: 393
1226611146
Aeropuertos clasificados: 281
Rutas por clasificar: 391
1161810257
Aeropuertos clasificados: 281
Rutas por clasificar: 389
1486913485
Aeropuertos clasificados: 281
Rutas por clasificar: 387
1348710141
L

Las opciones para el destino de la ruta 1143310577 son: ['BGM']
Aeropuertos clasificados: 284
Rutas por clasificar: 303
1129810299
Aeropuertos clasificados: 284
Rutas por clasificar: 301
1410012339
Aeropuertos clasificados: 284
Rutas por clasificar: 299
1029910170
Las opciones para el destino de la ruta 1029910170 son: ['ADQ']
Aeropuertos clasificados: 285
Rutas por clasificar: 297
1410911298
Aeropuertos clasificados: 285
Rutas por clasificar: 296
1143315370
Aeropuertos clasificados: 285
Rutas por clasificar: 294
1143312992
Aeropuertos clasificados: 285
Rutas por clasificar: 292
1104214635
Aeropuertos clasificados: 285
Rutas por clasificar: 290
1052914635
Aeropuertos clasificados: 285
Rutas por clasificar: 288
1119310721
Aeropuertos clasificados: 285
Rutas por clasificar: 286
1119313244
Aeropuertos clasificados: 285
Rutas por clasificar: 284
1129813485
Aeropuertos clasificados: 285
Rutas por clasificar: 282
1385110821
Aeropuertos clasificados: 285
Rutas por clasificar: 280
{'14747': 'S

Las opciones para el destino de la ruta 1169712265 son: ['IAG']
Aeropuertos clasificados: 287
Rutas por clasificar: 193
1029912892
Aeropuertos clasificados: 287
Rutas por clasificar: 191
1129214635
Aeropuertos clasificados: 287
Rutas por clasificar: 189
1535611697
Aeropuertos clasificados: 287
Rutas por clasificar: 187
1483112982
Aeropuertos clasificados: 287
Rutas por clasificar: 185
1295311996
Aeropuertos clasificados: 287
Rutas por clasificar: 184
1105714843
Aeropuertos clasificados: 287
Rutas por clasificar: 182
1143310994
Aeropuertos clasificados: 287
Rutas por clasificar: 180
{'14747': 'SEA', '11298': 'DFW', '14831': 'SJC', '14771': 'SFO', '13487': 'MSP', '12889': 'LAS', '12892': 'LAX', '12264': 'IAD', '13303': 'MIA', '11057': 'CLT', '13930': 'ORD', '14869': 'SLC', '10693': 'BNA', '10299': 'ANC', '12266': 'IAH', '11292': 'DEN', '12478': 'JFK', '14107': 'PHX', '14057': 'PDX', '10397': 'ATL', '13198': 'MCI', '11630': 'FAI', '12173': 'HNL', '10732': 'BQN', '11618': 'EWR', '14254': '

Las opciones para el destino de la ruta 1129213502 son: ['MTJ', 'HYA']
No existen más rutas alternativas para este path 1129213502
1350211292
Las opciones para el origen de la ruta 1350211292 son: ['MTJ', 'HYA']
No existen más rutas alternativas para este path 1350211292
1119311057
Aeropuertos clasificados: 289
Rutas por clasificar: 56
1197315624
Aeropuertos clasificados: 289
Rutas por clasificar: 55
1295312339
Aeropuertos clasificados: 289
Rutas por clasificar: 53
1143310874
Aeropuertos clasificados: 289
Rutas por clasificar: 51
1348712173
Aeropuertos clasificados: 289
Rutas por clasificar: 49
1348712945
Aeropuertos clasificados: 289
Rutas por clasificar: 47
1058111618
Aeropuertos clasificados: 289
Rutas por clasificar: 46
1143313367
Aeropuertos clasificados: 289
Rutas por clasificar: 45
1336713487
Aeropuertos clasificados: 289
Rutas por clasificar: 44
1226414843
Aeropuertos clasificados: 289
Rutas por clasificar: 42
1226415024
Aeropuertos clasificados: 289
Rutas por clasificar: 40
{'

Las opciones para el destino de la ruta 1129812891 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129812891
1129811905
Las opciones para el destino de la ruta 1129811905 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129811905
1129814960
Las opciones para el destino de la ruta 1129814960 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1129814960
1039713795
Las opciones para el destino de la ruta 1039713795 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1039713795
1348711898
Las opciones para el destino de la ruta 1348711898 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1348711898
1225511292
Las opciones para el origen de la ruta 1225511292 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1225511292
1190511298
Las opciones para el origen de la ruta 1190511298 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1190511298
1486911097
Las opci

Las opciones para el origen de la ruta 1538914869 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1538914869
1101311433
Las opciones para el origen de la ruta 1101311433 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1101311433
1129212255
Las opciones para el destino de la ruta 1129212255 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1129212255
1189813487
Las opciones para el origen de la ruta 1189813487 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1189813487
1393015295
Las opciones para el destino de la ruta 1393015295 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393015295
1055110299
Las opciones para el origen de la ruta 1055110299 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1055110299
1129812891
Las opciones para el destino de la ruta 1129812891 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129812891
1129811905
Las opcion

Las opciones para el origen de la ruta 1496011298 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1496011298
1120313930
Las opciones para el origen de la ruta 1120313930 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1120313930
1379510397
Las opciones para el origen de la ruta 1379510397 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1379510397
1529513930
Las opciones para el origen de la ruta 1529513930 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1529513930
1288811292
Las opciones para el origen de la ruta 1288811292 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1288811292
1029910551
Las opciones para el destino de la ruta 1029910551 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1029910551
1538914869
Las opciones para el origen de la ruta 1538914869 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1538914869
1101311433
Las opciones

Las opciones para el destino de la ruta 1477114487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1477114487
1129213502
Las opciones para el destino de la ruta 1129213502 son: ['MTJ', 'HYA']
No existen más rutas alternativas para este path 1129213502
1350211292
Las opciones para el origen de la ruta 1350211292 son: ['MTJ', 'HYA']
No existen más rutas alternativas para este path 1350211292
1448714771
Las opciones para el origen de la ruta 1448714771 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1448714771
1063113487
Las opciones para el origen de la ruta 1063113487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1063113487
1289111298
Las opciones para el origen de la ruta 1289111298 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1289111298
1496011298
Las opciones para el origen de la ruta 1496011298 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1496011298
1120313930
Las opcione

Las opciones para el destino de la ruta 1348710631 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1348710631
1129212888
Las opciones para el destino de la ruta 1129212888 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1129212888
1486915389
Las opciones para el destino de la ruta 1486915389 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1486915389
1143311013
Las opciones para el destino de la ruta 1143311013 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1143311013
1393011203
Las opciones para el destino de la ruta 1393011203 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393011203
1109714869
Las opciones para el origen de la ruta 1109714869 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1109714869
1477114487
Las opciones para el destino de la ruta 1477114487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1477114487
1129213502
Las opc

Las opciones para el destino de la ruta 1129814960 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1129814960
1039713795
Las opciones para el destino de la ruta 1039713795 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1039713795
1348711898
Las opciones para el destino de la ruta 1348711898 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1348711898
1225511292
Las opciones para el origen de la ruta 1225511292 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1225511292
1190511298
Las opciones para el origen de la ruta 1190511298 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1190511298
1486911097
Las opciones para el destino de la ruta 1486911097 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1486911097
1348710631
Las opciones para el destino de la ruta 1348710631 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1348710631
1129212888
Las opci

Las opciones para el destino de la ruta 1129212255 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1129212255
1189813487
Las opciones para el origen de la ruta 1189813487 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1189813487
1393015295
Las opciones para el destino de la ruta 1393015295 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393015295
1055110299
Las opciones para el origen de la ruta 1055110299 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1055110299
1129812891
Las opciones para el destino de la ruta 1129812891 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129812891
1129811905
Las opciones para el destino de la ruta 1129811905 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129811905
1129814960
Las opciones para el destino de la ruta 1129814960 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1129814960
1039713795
Las opci

Las opciones para el origen de la ruta 1379510397 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1379510397
1529513930
Las opciones para el origen de la ruta 1529513930 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1529513930
1288811292
Las opciones para el origen de la ruta 1288811292 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1288811292
1029910551
Las opciones para el destino de la ruta 1029910551 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1029910551
1538914869
Las opciones para el origen de la ruta 1538914869 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1538914869
1101311433
Las opciones para el origen de la ruta 1101311433 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1101311433
1129212255
Las opciones para el destino de la ruta 1129212255 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1129212255
1189813487
Las opcione

Las opciones para el origen de la ruta 1350211292 son: ['MTJ', 'HYA']
No existen más rutas alternativas para este path 1350211292
1448714771
Las opciones para el origen de la ruta 1448714771 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1448714771
1063113487
Las opciones para el origen de la ruta 1063113487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1063113487
1289111298
Las opciones para el origen de la ruta 1289111298 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1289111298
1496011298
Las opciones para el origen de la ruta 1496011298 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1496011298
1120313930
Las opciones para el origen de la ruta 1120313930 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1120313930
1379510397
Las opciones para el origen de la ruta 1379510397 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1379510397
1529513930
Las opciones 

Las opciones para el destino de la ruta 1486915389 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1486915389
1143311013
Las opciones para el destino de la ruta 1143311013 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1143311013
1393011203
Las opciones para el destino de la ruta 1393011203 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393011203
1109714869
Las opciones para el origen de la ruta 1109714869 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1109714869
1477114487
Las opciones para el destino de la ruta 1477114487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1477114487
1129213502
Las opciones para el destino de la ruta 1129213502 son: ['MTJ', 'HYA']
No existen más rutas alternativas para este path 1129213502
1350211292
Las opciones para el origen de la ruta 1350211292 son: ['MTJ', 'HYA']
No existen más rutas alternativas para este path 1350211292
1448714771
Las opci

Las opciones para el destino de la ruta 1348711898 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1348711898
1225511292
Las opciones para el origen de la ruta 1225511292 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1225511292
1190511298
Las opciones para el origen de la ruta 1190511298 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1190511298
1486911097
Las opciones para el destino de la ruta 1486911097 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1486911097
1348710631
Las opciones para el destino de la ruta 1348710631 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1348710631
1129212888
Las opciones para el destino de la ruta 1129212888 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1129212888
1486915389
Las opciones para el destino de la ruta 1486915389 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1486915389
1143311013
Las opci

Las opciones para el destino de la ruta 1393015295 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393015295
1055110299
Las opciones para el origen de la ruta 1055110299 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1055110299
1129812891
Las opciones para el destino de la ruta 1129812891 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129812891
1129811905
Las opciones para el destino de la ruta 1129811905 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129811905
1129814960
Las opciones para el destino de la ruta 1129814960 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1129814960
1039713795
Las opciones para el destino de la ruta 1039713795 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1039713795
1348711898
Las opciones para el destino de la ruta 1348711898 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1348711898
1225511292
Las opc

Las opciones para el origen de la ruta 1288811292 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1288811292
1029910551
Las opciones para el destino de la ruta 1029910551 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1029910551
1538914869
Las opciones para el origen de la ruta 1538914869 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1538914869
1101311433
Las opciones para el origen de la ruta 1101311433 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1101311433
1129212255
Las opciones para el destino de la ruta 1129212255 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1129212255
1189813487
Las opciones para el origen de la ruta 1189813487 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1189813487
1393015295
Las opciones para el destino de la ruta 1393015295 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393015295
1055110299
Las opcion

Las opciones para el origen de la ruta 1063113487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1063113487
1289111298
Las opciones para el origen de la ruta 1289111298 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1289111298
1496011298
Las opciones para el origen de la ruta 1496011298 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1496011298
1120313930
Las opciones para el origen de la ruta 1120313930 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1120313930
1379510397
Las opciones para el origen de la ruta 1379510397 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1379510397
1529513930
Las opciones para el origen de la ruta 1529513930 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1529513930
1288811292
Las opciones para el origen de la ruta 1288811292 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1288811292
1029910551
Las opciones 

Las opciones para el destino de la ruta 1393011203 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393011203
1109714869
Las opciones para el origen de la ruta 1109714869 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1109714869
1477114487
Las opciones para el destino de la ruta 1477114487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1477114487
1129213502
Las opciones para el destino de la ruta 1129213502 son: ['MTJ', 'HYA']
No existen más rutas alternativas para este path 1129213502
1350211292
Las opciones para el origen de la ruta 1350211292 son: ['MTJ', 'HYA']
No existen más rutas alternativas para este path 1350211292
1448714771
Las opciones para el origen de la ruta 1448714771 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1448714771
1063113487
Las opciones para el origen de la ruta 1063113487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1063113487
1289111298
Las opcion

Las opciones para el origen de la ruta 1190511298 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1190511298
1486911097
Las opciones para el destino de la ruta 1486911097 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1486911097
1348710631
Las opciones para el destino de la ruta 1348710631 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1348710631
1129212888
Las opciones para el destino de la ruta 1129212888 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1129212888
1486915389
Las opciones para el destino de la ruta 1486915389 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1486915389
1143311013
Las opciones para el destino de la ruta 1143311013 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1143311013
1393011203
Las opciones para el destino de la ruta 1393011203 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393011203
1109714869
Las opc

Las opciones para el destino de la ruta 1129812891 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129812891
1129811905
Las opciones para el destino de la ruta 1129811905 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129811905
1129814960
Las opciones para el destino de la ruta 1129814960 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1129814960
1039713795
Las opciones para el destino de la ruta 1039713795 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1039713795
1348711898
Las opciones para el destino de la ruta 1348711898 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1348711898
1225511292
Las opciones para el origen de la ruta 1225511292 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1225511292
1190511298
Las opciones para el origen de la ruta 1190511298 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1190511298
1486911097
Las opci

Las opciones para el origen de la ruta 1538914869 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1538914869
1101311433
Las opciones para el origen de la ruta 1101311433 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1101311433
1129212255
Las opciones para el destino de la ruta 1129212255 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1129212255
1189813487
Las opciones para el origen de la ruta 1189813487 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1189813487
1393015295
Las opciones para el destino de la ruta 1393015295 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393015295
1055110299
Las opciones para el origen de la ruta 1055110299 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1055110299
1129812891
Las opciones para el destino de la ruta 1129812891 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129812891
1129811905
Las opcion

Las opciones para el origen de la ruta 1496011298 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1496011298
1120313930
Las opciones para el origen de la ruta 1120313930 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1120313930
1379510397
Las opciones para el origen de la ruta 1379510397 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1379510397
1529513930
Las opciones para el origen de la ruta 1529513930 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1529513930
1288811292
Las opciones para el origen de la ruta 1288811292 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1288811292
1029910551
Las opciones para el destino de la ruta 1029910551 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1029910551
1538914869
Las opciones para el origen de la ruta 1538914869 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1538914869
1101311433
Las opciones

Las opciones para el destino de la ruta 1477114487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1477114487
1129213502
Las opciones para el destino de la ruta 1129213502 son: ['MTJ', 'HYA']
No existen más rutas alternativas para este path 1129213502
1350211292
Las opciones para el origen de la ruta 1350211292 son: ['MTJ', 'HYA']
No existen más rutas alternativas para este path 1350211292
1448714771
Las opciones para el origen de la ruta 1448714771 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1448714771
1063113487
Las opciones para el origen de la ruta 1063113487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1063113487
1289111298
Las opciones para el origen de la ruta 1289111298 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1289111298
1496011298
Las opciones para el origen de la ruta 1496011298 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1496011298
1120313930
Las opcione

Las opciones para el destino de la ruta 1348710631 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1348710631
1129212888
Las opciones para el destino de la ruta 1129212888 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1129212888
1486915389
Las opciones para el destino de la ruta 1486915389 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1486915389
1143311013
Las opciones para el destino de la ruta 1143311013 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1143311013
1393011203
Las opciones para el destino de la ruta 1393011203 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393011203
1109714869
Las opciones para el origen de la ruta 1109714869 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1109714869
1477114487
Las opciones para el destino de la ruta 1477114487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1477114487
1129213502
Las opc

Las opciones para el destino de la ruta 1129814960 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1129814960
1039713795
Las opciones para el destino de la ruta 1039713795 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1039713795
1348711898
Las opciones para el destino de la ruta 1348711898 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1348711898
1225511292
Las opciones para el origen de la ruta 1225511292 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1225511292
1190511298
Las opciones para el origen de la ruta 1190511298 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1190511298
1486911097
Las opciones para el destino de la ruta 1486911097 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1486911097
1348710631
Las opciones para el destino de la ruta 1348710631 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1348710631
1129212888
Las opci

Las opciones para el destino de la ruta 1129212255 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1129212255
1189813487
Las opciones para el origen de la ruta 1189813487 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1189813487
1393015295
Las opciones para el destino de la ruta 1393015295 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393015295
1055110299
Las opciones para el origen de la ruta 1055110299 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1055110299
1129812891
Las opciones para el destino de la ruta 1129812891 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129812891
1129811905
Las opciones para el destino de la ruta 1129811905 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129811905
1129814960
Las opciones para el destino de la ruta 1129814960 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1129814960
1039713795
Las opci

Las opciones para el origen de la ruta 1379510397 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1379510397
1529513930
Las opciones para el origen de la ruta 1529513930 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1529513930
1288811292
Las opciones para el origen de la ruta 1288811292 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1288811292
1029910551
Las opciones para el destino de la ruta 1029910551 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1029910551
1538914869
Las opciones para el origen de la ruta 1538914869 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1538914869
1101311433
Las opciones para el origen de la ruta 1101311433 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1101311433
1129212255
Las opciones para el destino de la ruta 1129212255 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1129212255
1189813487
Las opcione

Las opciones para el origen de la ruta 1350211292 son: ['MTJ', 'HYA']
No existen más rutas alternativas para este path 1350211292
1448714771
Las opciones para el origen de la ruta 1448714771 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1448714771
1063113487
Las opciones para el origen de la ruta 1063113487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1063113487
1289111298
Las opciones para el origen de la ruta 1289111298 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1289111298
1496011298
Las opciones para el origen de la ruta 1496011298 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1496011298
1120313930
Las opciones para el origen de la ruta 1120313930 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1120313930
1379510397
Las opciones para el origen de la ruta 1379510397 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1379510397
1529513930
Las opciones 

Las opciones para el destino de la ruta 1486915389 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1486915389
1143311013
Las opciones para el destino de la ruta 1143311013 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1143311013
1393011203
Las opciones para el destino de la ruta 1393011203 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393011203
1109714869
Las opciones para el origen de la ruta 1109714869 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1109714869
1477114487
Las opciones para el destino de la ruta 1477114487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1477114487
1129213502
Las opciones para el destino de la ruta 1129213502 son: ['MTJ', 'HYA']
No existen más rutas alternativas para este path 1129213502
1350211292
Las opciones para el origen de la ruta 1350211292 son: ['MTJ', 'HYA']
No existen más rutas alternativas para este path 1350211292
1448714771
Las opci

Las opciones para el destino de la ruta 1348711898 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1348711898
1225511292
Las opciones para el origen de la ruta 1225511292 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1225511292
1190511298
Las opciones para el origen de la ruta 1190511298 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1190511298
1486911097
Las opciones para el destino de la ruta 1486911097 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1486911097
1348710631
Las opciones para el destino de la ruta 1348710631 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1348710631
1129212888
Las opciones para el destino de la ruta 1129212888 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1129212888
1486915389
Las opciones para el destino de la ruta 1486915389 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1486915389
1143311013
Las opci

Las opciones para el destino de la ruta 1393015295 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393015295
1055110299
Las opciones para el origen de la ruta 1055110299 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1055110299
1129812891
Las opciones para el destino de la ruta 1129812891 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129812891
1129811905
Las opciones para el destino de la ruta 1129811905 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129811905
1129814960
Las opciones para el destino de la ruta 1129814960 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1129814960
1039713795
Las opciones para el destino de la ruta 1039713795 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1039713795
1348711898
Las opciones para el destino de la ruta 1348711898 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1348711898
1225511292
Las opc

Las opciones para el origen de la ruta 1288811292 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1288811292
1029910551
Las opciones para el destino de la ruta 1029910551 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1029910551
1538914869
Las opciones para el origen de la ruta 1538914869 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1538914869
1101311433
Las opciones para el origen de la ruta 1101311433 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1101311433
1129212255
Las opciones para el destino de la ruta 1129212255 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1129212255
1189813487
Las opciones para el origen de la ruta 1189813487 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1189813487
1393015295
Las opciones para el destino de la ruta 1393015295 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393015295
1055110299
Las opcion

Las opciones para el origen de la ruta 1063113487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1063113487
1289111298
Las opciones para el origen de la ruta 1289111298 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1289111298
1496011298
Las opciones para el origen de la ruta 1496011298 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1496011298
1120313930
Las opciones para el origen de la ruta 1120313930 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1120313930
1379510397
Las opciones para el origen de la ruta 1379510397 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1379510397
1529513930
Las opciones para el origen de la ruta 1529513930 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1529513930
1288811292
Las opciones para el origen de la ruta 1288811292 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1288811292
1029910551
Las opciones 

Las opciones para el destino de la ruta 1393011203 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393011203
1109714869
Las opciones para el origen de la ruta 1109714869 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1109714869
1477114487
Las opciones para el destino de la ruta 1477114487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1477114487
1129213502
Las opciones para el destino de la ruta 1129213502 son: ['MTJ', 'HYA']
No existen más rutas alternativas para este path 1129213502
1350211292
Las opciones para el origen de la ruta 1350211292 son: ['MTJ', 'HYA']
No existen más rutas alternativas para este path 1350211292
1448714771
Las opciones para el origen de la ruta 1448714771 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1448714771
1063113487
Las opciones para el origen de la ruta 1063113487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1063113487
1289111298
Las opcion

Las opciones para el origen de la ruta 1190511298 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1190511298
1486911097
Las opciones para el destino de la ruta 1486911097 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1486911097
1348710631
Las opciones para el destino de la ruta 1348710631 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1348710631
1129212888
Las opciones para el destino de la ruta 1129212888 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1129212888
1486915389
Las opciones para el destino de la ruta 1486915389 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1486915389
1143311013
Las opciones para el destino de la ruta 1143311013 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1143311013
1393011203
Las opciones para el destino de la ruta 1393011203 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393011203
1109714869
Las opc

Las opciones para el destino de la ruta 1129812891 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129812891
1129811905
Las opciones para el destino de la ruta 1129811905 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129811905
1129814960
Las opciones para el destino de la ruta 1129814960 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1129814960
1039713795
Las opciones para el destino de la ruta 1039713795 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1039713795
1348711898
Las opciones para el destino de la ruta 1348711898 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1348711898
1225511292
Las opciones para el origen de la ruta 1225511292 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1225511292
1190511298
Las opciones para el origen de la ruta 1190511298 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1190511298
1486911097
Las opci

Las opciones para el origen de la ruta 1538914869 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1538914869
1101311433
Las opciones para el origen de la ruta 1101311433 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1101311433
1129212255
Las opciones para el destino de la ruta 1129212255 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1129212255
1189813487
Las opciones para el origen de la ruta 1189813487 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1189813487
1393015295
Las opciones para el destino de la ruta 1393015295 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393015295
1055110299
Las opciones para el origen de la ruta 1055110299 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1055110299
1129812891
Las opciones para el destino de la ruta 1129812891 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129812891
1129811905
Las opcion

Las opciones para el origen de la ruta 1496011298 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1496011298
1120313930
Las opciones para el origen de la ruta 1120313930 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1120313930
1379510397
Las opciones para el origen de la ruta 1379510397 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1379510397
1529513930
Las opciones para el origen de la ruta 1529513930 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1529513930
1288811292
Las opciones para el origen de la ruta 1288811292 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1288811292
1029910551
Las opciones para el destino de la ruta 1029910551 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1029910551
1538914869
Las opciones para el origen de la ruta 1538914869 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1538914869
1101311433
Las opciones

Las opciones para el destino de la ruta 1477114487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1477114487
1129213502
Las opciones para el destino de la ruta 1129213502 son: ['MTJ', 'HYA']
No existen más rutas alternativas para este path 1129213502
1350211292
Las opciones para el origen de la ruta 1350211292 son: ['MTJ', 'HYA']
No existen más rutas alternativas para este path 1350211292
1448714771
Las opciones para el origen de la ruta 1448714771 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1448714771
1063113487
Las opciones para el origen de la ruta 1063113487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1063113487
1289111298
Las opciones para el origen de la ruta 1289111298 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1289111298
1496011298
Las opciones para el origen de la ruta 1496011298 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1496011298
1120313930
Las opcione

Las opciones para el destino de la ruta 1348710631 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1348710631
1129212888
Las opciones para el destino de la ruta 1129212888 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1129212888
1486915389
Las opciones para el destino de la ruta 1486915389 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1486915389
1143311013
Las opciones para el destino de la ruta 1143311013 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1143311013
1393011203
Las opciones para el destino de la ruta 1393011203 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393011203
1109714869
Las opciones para el origen de la ruta 1109714869 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1109714869
1477114487
Las opciones para el destino de la ruta 1477114487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1477114487
1129213502
Las opc

Las opciones para el destino de la ruta 1129814960 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1129814960
1039713795
Las opciones para el destino de la ruta 1039713795 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1039713795
1348711898
Las opciones para el destino de la ruta 1348711898 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1348711898
1225511292
Las opciones para el origen de la ruta 1225511292 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1225511292
1190511298
Las opciones para el origen de la ruta 1190511298 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1190511298
1486911097
Las opciones para el destino de la ruta 1486911097 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1486911097
1348710631
Las opciones para el destino de la ruta 1348710631 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1348710631
1129212888
Las opci

Las opciones para el destino de la ruta 1129212255 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1129212255
1189813487
Las opciones para el origen de la ruta 1189813487 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1189813487
1393015295
Las opciones para el destino de la ruta 1393015295 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393015295
1055110299
Las opciones para el origen de la ruta 1055110299 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1055110299
1129812891
Las opciones para el destino de la ruta 1129812891 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129812891
1129811905
Las opciones para el destino de la ruta 1129811905 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129811905
1129814960
Las opciones para el destino de la ruta 1129814960 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1129814960
1039713795
Las opci

Las opciones para el origen de la ruta 1379510397 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1379510397
1529513930
Las opciones para el origen de la ruta 1529513930 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1529513930
1288811292
Las opciones para el origen de la ruta 1288811292 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1288811292
1029910551
Las opciones para el destino de la ruta 1029910551 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1029910551
1538914869
Las opciones para el origen de la ruta 1538914869 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1538914869
1101311433
Las opciones para el origen de la ruta 1101311433 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1101311433
1129212255
Las opciones para el destino de la ruta 1129212255 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1129212255
1189813487
Las opcione

Las opciones para el origen de la ruta 1350211292 son: ['MTJ', 'HYA']
No existen más rutas alternativas para este path 1350211292
1448714771
Las opciones para el origen de la ruta 1448714771 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1448714771
1063113487
Las opciones para el origen de la ruta 1063113487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1063113487
1289111298
Las opciones para el origen de la ruta 1289111298 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1289111298
1496011298
Las opciones para el origen de la ruta 1496011298 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1496011298
1120313930
Las opciones para el origen de la ruta 1120313930 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1120313930
1379510397
Las opciones para el origen de la ruta 1379510397 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1379510397
1529513930
Las opciones 

Las opciones para el destino de la ruta 1486915389 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1486915389
1143311013
Las opciones para el destino de la ruta 1143311013 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1143311013
1393011203
Las opciones para el destino de la ruta 1393011203 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393011203
1109714869
Las opciones para el origen de la ruta 1109714869 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1109714869
1477114487
Las opciones para el destino de la ruta 1477114487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1477114487
1129213502
Las opciones para el destino de la ruta 1129213502 son: ['MTJ', 'HYA']
No existen más rutas alternativas para este path 1129213502
1350211292
Las opciones para el origen de la ruta 1350211292 son: ['MTJ', 'HYA']
No existen más rutas alternativas para este path 1350211292
1448714771
Las opci

Las opciones para el destino de la ruta 1348711898 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1348711898
1225511292
Las opciones para el origen de la ruta 1225511292 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1225511292
1190511298
Las opciones para el origen de la ruta 1190511298 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1190511298
1486911097
Las opciones para el destino de la ruta 1486911097 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1486911097
1348710631
Las opciones para el destino de la ruta 1348710631 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1348710631
1129212888
Las opciones para el destino de la ruta 1129212888 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1129212888
1486915389
Las opciones para el destino de la ruta 1486915389 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1486915389
1143311013
Las opci

Las opciones para el destino de la ruta 1393015295 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393015295
1055110299
Las opciones para el origen de la ruta 1055110299 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1055110299
1129812891
Las opciones para el destino de la ruta 1129812891 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129812891
1129811905
Las opciones para el destino de la ruta 1129811905 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129811905
1129814960
Las opciones para el destino de la ruta 1129814960 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1129814960
1039713795
Las opciones para el destino de la ruta 1039713795 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1039713795
1348711898
Las opciones para el destino de la ruta 1348711898 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1348711898
1225511292
Las opc

Las opciones para el origen de la ruta 1288811292 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1288811292
1029910551
Las opciones para el destino de la ruta 1029910551 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1029910551
1538914869
Las opciones para el origen de la ruta 1538914869 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1538914869
1101311433
Las opciones para el origen de la ruta 1101311433 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1101311433
1129212255
Las opciones para el destino de la ruta 1129212255 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1129212255
1189813487
Las opciones para el origen de la ruta 1189813487 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1189813487
1393015295
Las opciones para el destino de la ruta 1393015295 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393015295
1055110299
Las opcion

Las opciones para el origen de la ruta 1063113487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1063113487
1289111298
Las opciones para el origen de la ruta 1289111298 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1289111298
1496011298
Las opciones para el origen de la ruta 1496011298 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1496011298
1120313930
Las opciones para el origen de la ruta 1120313930 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1120313930
1379510397
Las opciones para el origen de la ruta 1379510397 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1379510397
1529513930
Las opciones para el origen de la ruta 1529513930 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1529513930
1288811292
Las opciones para el origen de la ruta 1288811292 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1288811292
1029910551
Las opciones 

Las opciones para el destino de la ruta 1393011203 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393011203
1109714869
Las opciones para el origen de la ruta 1109714869 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1109714869
1477114487
Las opciones para el destino de la ruta 1477114487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1477114487
1129213502
Las opciones para el destino de la ruta 1129213502 son: ['MTJ', 'HYA']
No existen más rutas alternativas para este path 1129213502
1350211292
Las opciones para el origen de la ruta 1350211292 son: ['MTJ', 'HYA']
No existen más rutas alternativas para este path 1350211292
1448714771
Las opciones para el origen de la ruta 1448714771 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1448714771
1063113487
Las opciones para el origen de la ruta 1063113487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1063113487
1289111298
Las opcion

Las opciones para el origen de la ruta 1190511298 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1190511298
1486911097
Las opciones para el destino de la ruta 1486911097 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1486911097
1348710631
Las opciones para el destino de la ruta 1348710631 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1348710631
1129212888
Las opciones para el destino de la ruta 1129212888 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1129212888
1486915389
Las opciones para el destino de la ruta 1486915389 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1486915389
1143311013
Las opciones para el destino de la ruta 1143311013 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1143311013
1393011203
Las opciones para el destino de la ruta 1393011203 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393011203
1109714869
Las opc

Las opciones para el destino de la ruta 1129812891 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129812891
1129811905
Las opciones para el destino de la ruta 1129811905 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129811905
1129814960
Las opciones para el destino de la ruta 1129814960 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1129814960
1039713795
Las opciones para el destino de la ruta 1039713795 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1039713795
1348711898
Las opciones para el destino de la ruta 1348711898 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1348711898
1225511292
Las opciones para el origen de la ruta 1225511292 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1225511292
1190511298
Las opciones para el origen de la ruta 1190511298 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1190511298
1486911097
Las opci

Las opciones para el origen de la ruta 1538914869 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1538914869
1101311433
Las opciones para el origen de la ruta 1101311433 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1101311433
1129212255
Las opciones para el destino de la ruta 1129212255 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1129212255
1189813487
Las opciones para el origen de la ruta 1189813487 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1189813487
1393015295
Las opciones para el destino de la ruta 1393015295 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393015295
1055110299
Las opciones para el origen de la ruta 1055110299 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1055110299
1129812891
Las opciones para el destino de la ruta 1129812891 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129812891
1129811905
Las opcion

Las opciones para el origen de la ruta 1496011298 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1496011298
1120313930
Las opciones para el origen de la ruta 1120313930 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1120313930
1379510397
Las opciones para el origen de la ruta 1379510397 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1379510397
1529513930
Las opciones para el origen de la ruta 1529513930 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1529513930
1288811292
Las opciones para el origen de la ruta 1288811292 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1288811292
1029910551
Las opciones para el destino de la ruta 1029910551 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1029910551
1538914869
Las opciones para el origen de la ruta 1538914869 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1538914869
1101311433
Las opciones

Las opciones para el destino de la ruta 1477114487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1477114487
1129213502
Las opciones para el destino de la ruta 1129213502 son: ['MTJ', 'HYA']
No existen más rutas alternativas para este path 1129213502
1350211292
Las opciones para el origen de la ruta 1350211292 son: ['MTJ', 'HYA']
No existen más rutas alternativas para este path 1350211292
1448714771
Las opciones para el origen de la ruta 1448714771 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1448714771
1063113487
Las opciones para el origen de la ruta 1063113487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1063113487
1289111298
Las opciones para el origen de la ruta 1289111298 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1289111298
1496011298
Las opciones para el origen de la ruta 1496011298 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1496011298
1120313930
Las opcione

Las opciones para el destino de la ruta 1348710631 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1348710631
1129212888
Las opciones para el destino de la ruta 1129212888 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1129212888
1486915389
Las opciones para el destino de la ruta 1486915389 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1486915389
1143311013
Las opciones para el destino de la ruta 1143311013 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1143311013
1393011203
Las opciones para el destino de la ruta 1393011203 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393011203
1109714869
Las opciones para el origen de la ruta 1109714869 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1109714869
1477114487
Las opciones para el destino de la ruta 1477114487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1477114487
1129213502
Las opc

Las opciones para el destino de la ruta 1129814960 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1129814960
1039713795
Las opciones para el destino de la ruta 1039713795 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1039713795
1348711898
Las opciones para el destino de la ruta 1348711898 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1348711898
1225511292
Las opciones para el origen de la ruta 1225511292 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1225511292
1190511298
Las opciones para el origen de la ruta 1190511298 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1190511298
1486911097
Las opciones para el destino de la ruta 1486911097 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1486911097
1348710631
Las opciones para el destino de la ruta 1348710631 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1348710631
1129212888
Las opci

Las opciones para el destino de la ruta 1129212255 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1129212255
1189813487
Las opciones para el origen de la ruta 1189813487 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1189813487
1393015295
Las opciones para el destino de la ruta 1393015295 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393015295
1055110299
Las opciones para el origen de la ruta 1055110299 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1055110299
1129812891
Las opciones para el destino de la ruta 1129812891 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129812891
1129811905
Las opciones para el destino de la ruta 1129811905 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129811905
1129814960
Las opciones para el destino de la ruta 1129814960 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1129814960
1039713795
Las opci

Las opciones para el origen de la ruta 1379510397 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1379510397
1529513930
Las opciones para el origen de la ruta 1529513930 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1529513930
1288811292
Las opciones para el origen de la ruta 1288811292 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1288811292
1029910551
Las opciones para el destino de la ruta 1029910551 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1029910551
1538914869
Las opciones para el origen de la ruta 1538914869 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1538914869
1101311433
Las opciones para el origen de la ruta 1101311433 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1101311433
1129212255
Las opciones para el destino de la ruta 1129212255 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1129212255
1189813487
Las opcione

Las opciones para el origen de la ruta 1350211292 son: ['MTJ', 'HYA']
No existen más rutas alternativas para este path 1350211292
1448714771
Las opciones para el origen de la ruta 1448714771 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1448714771
1063113487
Las opciones para el origen de la ruta 1063113487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1063113487
1289111298
Las opciones para el origen de la ruta 1289111298 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1289111298
1496011298
Las opciones para el origen de la ruta 1496011298 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1496011298
1120313930
Las opciones para el origen de la ruta 1120313930 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1120313930
1379510397
Las opciones para el origen de la ruta 1379510397 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1379510397
1529513930
Las opciones 

Las opciones para el destino de la ruta 1486915389 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1486915389
1143311013
Las opciones para el destino de la ruta 1143311013 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1143311013
1393011203
Las opciones para el destino de la ruta 1393011203 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393011203
1109714869
Las opciones para el origen de la ruta 1109714869 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1109714869
1477114487
Las opciones para el destino de la ruta 1477114487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1477114487
1129213502
Las opciones para el destino de la ruta 1129213502 son: ['MTJ', 'HYA']
No existen más rutas alternativas para este path 1129213502
1350211292
Las opciones para el origen de la ruta 1350211292 son: ['MTJ', 'HYA']
No existen más rutas alternativas para este path 1350211292
1448714771
Las opci

Las opciones para el destino de la ruta 1348711898 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1348711898
1225511292
Las opciones para el origen de la ruta 1225511292 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1225511292
1190511298
Las opciones para el origen de la ruta 1190511298 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1190511298
1486911097
Las opciones para el destino de la ruta 1486911097 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1486911097
1348710631
Las opciones para el destino de la ruta 1348710631 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1348710631
1129212888
Las opciones para el destino de la ruta 1129212888 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1129212888
1486915389
Las opciones para el destino de la ruta 1486915389 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1486915389
1143311013
Las opci

Las opciones para el destino de la ruta 1393015295 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393015295
1055110299
Las opciones para el origen de la ruta 1055110299 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1055110299
1129812891
Las opciones para el destino de la ruta 1129812891 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129812891
1129811905
Las opciones para el destino de la ruta 1129811905 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129811905
1129814960
Las opciones para el destino de la ruta 1129814960 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1129814960
1039713795
Las opciones para el destino de la ruta 1039713795 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1039713795
1348711898
Las opciones para el destino de la ruta 1348711898 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1348711898
1225511292
Las opc

Las opciones para el origen de la ruta 1288811292 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1288811292
1029910551
Las opciones para el destino de la ruta 1029910551 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1029910551
1538914869
Las opciones para el origen de la ruta 1538914869 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1538914869
1101311433
Las opciones para el origen de la ruta 1101311433 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1101311433
1129212255
Las opciones para el destino de la ruta 1129212255 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1129212255
1189813487
Las opciones para el origen de la ruta 1189813487 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1189813487
1393015295
Las opciones para el destino de la ruta 1393015295 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393015295
1055110299
Las opcion

Las opciones para el origen de la ruta 1063113487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1063113487
1289111298
Las opciones para el origen de la ruta 1289111298 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1289111298
1496011298
Las opciones para el origen de la ruta 1496011298 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1496011298
1120313930
Las opciones para el origen de la ruta 1120313930 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1120313930
1379510397
Las opciones para el origen de la ruta 1379510397 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1379510397
1529513930
Las opciones para el origen de la ruta 1529513930 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1529513930
1288811292
Las opciones para el origen de la ruta 1288811292 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1288811292
1029910551
Las opciones 

Las opciones para el destino de la ruta 1393011203 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393011203
1109714869
Las opciones para el origen de la ruta 1109714869 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1109714869
1477114487
Las opciones para el destino de la ruta 1477114487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1477114487
1129213502
Las opciones para el destino de la ruta 1129213502 son: ['MTJ', 'HYA']
No existen más rutas alternativas para este path 1129213502
1350211292
Las opciones para el origen de la ruta 1350211292 son: ['MTJ', 'HYA']
No existen más rutas alternativas para este path 1350211292
1448714771
Las opciones para el origen de la ruta 1448714771 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1448714771
1063113487
Las opciones para el origen de la ruta 1063113487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1063113487
1289111298
Las opcion

Las opciones para el origen de la ruta 1190511298 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1190511298
1486911097
Las opciones para el destino de la ruta 1486911097 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1486911097
1348710631
Las opciones para el destino de la ruta 1348710631 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1348710631
1129212888
Las opciones para el destino de la ruta 1129212888 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1129212888
1486915389
Las opciones para el destino de la ruta 1486915389 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1486915389
1143311013
Las opciones para el destino de la ruta 1143311013 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1143311013
1393011203
Las opciones para el destino de la ruta 1393011203 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393011203
1109714869
Las opc

Las opciones para el destino de la ruta 1129812891 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129812891
1129811905
Las opciones para el destino de la ruta 1129811905 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129811905
1129814960
Las opciones para el destino de la ruta 1129814960 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1129814960
1039713795
Las opciones para el destino de la ruta 1039713795 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1039713795
1348711898
Las opciones para el destino de la ruta 1348711898 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1348711898
1225511292
Las opciones para el origen de la ruta 1225511292 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1225511292
1190511298
Las opciones para el origen de la ruta 1190511298 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1190511298
1486911097
Las opci

Las opciones para el origen de la ruta 1538914869 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1538914869
1101311433
Las opciones para el origen de la ruta 1101311433 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1101311433
1129212255
Las opciones para el destino de la ruta 1129212255 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1129212255
1189813487
Las opciones para el origen de la ruta 1189813487 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1189813487
1393015295
Las opciones para el destino de la ruta 1393015295 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393015295
1055110299
Las opciones para el origen de la ruta 1055110299 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1055110299
1129812891
Las opciones para el destino de la ruta 1129812891 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129812891
1129811905
Las opcion

Las opciones para el origen de la ruta 1496011298 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1496011298
1120313930
Las opciones para el origen de la ruta 1120313930 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1120313930
1379510397
Las opciones para el origen de la ruta 1379510397 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1379510397
1529513930
Las opciones para el origen de la ruta 1529513930 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1529513930
1288811292
Las opciones para el origen de la ruta 1288811292 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1288811292
1029910551
Las opciones para el destino de la ruta 1029910551 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1029910551
1538914869
Las opciones para el origen de la ruta 1538914869 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1538914869
1101311433
Las opciones

Las opciones para el destino de la ruta 1477114487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1477114487
1129213502
Las opciones para el destino de la ruta 1129213502 son: ['MTJ', 'HYA']
No existen más rutas alternativas para este path 1129213502
1350211292
Las opciones para el origen de la ruta 1350211292 son: ['MTJ', 'HYA']
No existen más rutas alternativas para este path 1350211292
1448714771
Las opciones para el origen de la ruta 1448714771 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1448714771
1063113487
Las opciones para el origen de la ruta 1063113487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1063113487
1289111298
Las opciones para el origen de la ruta 1289111298 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1289111298
1496011298
Las opciones para el origen de la ruta 1496011298 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1496011298
1120313930
Las opcione

Las opciones para el destino de la ruta 1348710631 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1348710631
1129212888
Las opciones para el destino de la ruta 1129212888 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1129212888
1486915389
Las opciones para el destino de la ruta 1486915389 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1486915389
1143311013
Las opciones para el destino de la ruta 1143311013 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1143311013
1393011203
Las opciones para el destino de la ruta 1393011203 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393011203
1109714869
Las opciones para el origen de la ruta 1109714869 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1109714869
1477114487
Las opciones para el destino de la ruta 1477114487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1477114487
1129213502
Las opc

Las opciones para el destino de la ruta 1129814960 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1129814960
1039713795
Las opciones para el destino de la ruta 1039713795 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1039713795
1348711898
Las opciones para el destino de la ruta 1348711898 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1348711898
1225511292
Las opciones para el origen de la ruta 1225511292 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1225511292
1190511298
Las opciones para el origen de la ruta 1190511298 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1190511298
1486911097
Las opciones para el destino de la ruta 1486911097 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1486911097
1348710631
Las opciones para el destino de la ruta 1348710631 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1348710631
1129212888
Las opci

Las opciones para el destino de la ruta 1129212255 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1129212255
1189813487
Las opciones para el origen de la ruta 1189813487 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1189813487
1393015295
Las opciones para el destino de la ruta 1393015295 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393015295
1055110299
Las opciones para el origen de la ruta 1055110299 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1055110299
1129812891
Las opciones para el destino de la ruta 1129812891 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129812891
1129811905
Las opciones para el destino de la ruta 1129811905 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129811905
1129814960
Las opciones para el destino de la ruta 1129814960 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1129814960
1039713795
Las opci

Las opciones para el origen de la ruta 1379510397 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1379510397
1529513930
Las opciones para el origen de la ruta 1529513930 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1529513930
1288811292
Las opciones para el origen de la ruta 1288811292 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1288811292
1029910551
Las opciones para el destino de la ruta 1029910551 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1029910551
1538914869
Las opciones para el origen de la ruta 1538914869 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1538914869
1101311433
Las opciones para el origen de la ruta 1101311433 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1101311433
1129212255
Las opciones para el destino de la ruta 1129212255 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1129212255
1189813487
Las opcione

Las opciones para el origen de la ruta 1350211292 son: ['MTJ', 'HYA']
No existen más rutas alternativas para este path 1350211292
1448714771
Las opciones para el origen de la ruta 1448714771 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1448714771
1063113487
Las opciones para el origen de la ruta 1063113487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1063113487
1289111298
Las opciones para el origen de la ruta 1289111298 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1289111298
1496011298
Las opciones para el origen de la ruta 1496011298 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1496011298
1120313930
Las opciones para el origen de la ruta 1120313930 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1120313930
1379510397
Las opciones para el origen de la ruta 1379510397 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1379510397
1529513930
Las opciones 

Las opciones para el destino de la ruta 1486915389 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1486915389
1143311013
Las opciones para el destino de la ruta 1143311013 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1143311013
1393011203
Las opciones para el destino de la ruta 1393011203 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393011203
1109714869
Las opciones para el origen de la ruta 1109714869 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1109714869
1477114487
Las opciones para el destino de la ruta 1477114487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1477114487
1129213502
Las opciones para el destino de la ruta 1129213502 son: ['MTJ', 'HYA']
No existen más rutas alternativas para este path 1129213502
1350211292
Las opciones para el origen de la ruta 1350211292 son: ['MTJ', 'HYA']
No existen más rutas alternativas para este path 1350211292
1448714771
Las opci

Las opciones para el destino de la ruta 1348711898 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1348711898
1225511292
Las opciones para el origen de la ruta 1225511292 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1225511292
1190511298
Las opciones para el origen de la ruta 1190511298 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1190511298
1486911097
Las opciones para el destino de la ruta 1486911097 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1486911097
1348710631
Las opciones para el destino de la ruta 1348710631 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1348710631
1129212888
Las opciones para el destino de la ruta 1129212888 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1129212888
1486915389
Las opciones para el destino de la ruta 1486915389 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1486915389
1143311013
Las opci

Las opciones para el destino de la ruta 1393015295 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393015295
1055110299
Las opciones para el origen de la ruta 1055110299 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1055110299
1129812891
Las opciones para el destino de la ruta 1129812891 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129812891
1129811905
Las opciones para el destino de la ruta 1129811905 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129811905
1129814960
Las opciones para el destino de la ruta 1129814960 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1129814960
1039713795
Las opciones para el destino de la ruta 1039713795 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1039713795
1348711898
Las opciones para el destino de la ruta 1348711898 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1348711898
1225511292
Las opc

Las opciones para el origen de la ruta 1288811292 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1288811292
1029910551
Las opciones para el destino de la ruta 1029910551 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1029910551
1538914869
Las opciones para el origen de la ruta 1538914869 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1538914869
1101311433
Las opciones para el origen de la ruta 1101311433 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1101311433
1129212255
Las opciones para el destino de la ruta 1129212255 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1129212255
1189813487
Las opciones para el origen de la ruta 1189813487 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1189813487
1393015295
Las opciones para el destino de la ruta 1393015295 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393015295
1055110299
Las opcion

Las opciones para el origen de la ruta 1063113487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1063113487
1289111298
Las opciones para el origen de la ruta 1289111298 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1289111298
1496011298
Las opciones para el origen de la ruta 1496011298 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1496011298
1120313930
Las opciones para el origen de la ruta 1120313930 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1120313930
1379510397
Las opciones para el origen de la ruta 1379510397 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1379510397
1529513930
Las opciones para el origen de la ruta 1529513930 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1529513930
1288811292
Las opciones para el origen de la ruta 1288811292 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1288811292
1029910551
Las opciones 

Las opciones para el destino de la ruta 1393011203 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393011203
1109714869
Las opciones para el origen de la ruta 1109714869 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1109714869
1477114487
Las opciones para el destino de la ruta 1477114487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1477114487
1129213502
Las opciones para el destino de la ruta 1129213502 son: ['MTJ', 'HYA']
No existen más rutas alternativas para este path 1129213502
1350211292
Las opciones para el origen de la ruta 1350211292 son: ['MTJ', 'HYA']
No existen más rutas alternativas para este path 1350211292
1448714771
Las opciones para el origen de la ruta 1448714771 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1448714771
1063113487
Las opciones para el origen de la ruta 1063113487 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1063113487
1289111298
Las opcion

Las opciones para el origen de la ruta 1190511298 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1190511298
1486911097
Las opciones para el destino de la ruta 1486911097 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1486911097
1348710631
Las opciones para el destino de la ruta 1348710631 son: ['BJI', 'RDD']
No existen más rutas alternativas para este path 1348710631
1129212888
Las opciones para el destino de la ruta 1129212888 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1129212888
1486915389
Las opciones para el destino de la ruta 1486915389 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1486915389
1143311013
Las opciones para el destino de la ruta 1143311013 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1143311013
1393011203
Las opciones para el destino de la ruta 1393011203 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393011203
1109714869
Las opc

Las opciones para el destino de la ruta 1129812891 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129812891
1129811905
Las opciones para el destino de la ruta 1129811905 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129811905
1129814960
Las opciones para el destino de la ruta 1129814960 son: ['SPS', 'LAR']
No existen más rutas alternativas para este path 1129814960
1039713795
Las opciones para el destino de la ruta 1039713795 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1039713795
1348711898
Las opciones para el destino de la ruta 1348711898 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1348711898
1225511292
Las opciones para el origen de la ruta 1225511292 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1225511292
1190511298
Las opciones para el origen de la ruta 1190511298 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1190511298
1486911097
Las opci

Las opciones para el origen de la ruta 1538914869 son: ['TWF', 'CWA']
No existen más rutas alternativas para este path 1538914869
1101311433
Las opciones para el origen de la ruta 1101311433 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1101311433
1129212255
Las opciones para el destino de la ruta 1129212255 son: ['HYS', 'COD']
No existen más rutas alternativas para este path 1129212255
1189813487
Las opciones para el origen de la ruta 1189813487 son: ['CIU', 'GFK']
No existen más rutas alternativas para este path 1189813487
1393015295
Las opciones para el destino de la ruta 1393015295 son: ['TOL', 'CWA']
No existen más rutas alternativas para este path 1393015295
1055110299
Las opciones para el origen de la ruta 1055110299 son: ['OAJ', 'BET']
No existen más rutas alternativas para este path 1055110299
1129812891
Las opciones para el destino de la ruta 1129812891 son: ['LAW', 'GGG']
No existen más rutas alternativas para este path 1129812891
1129811905
Las opcion

KeyboardInterrupt: 

In [37]:
dict_airport

{'14747': 'SEA',
 '11298': 'DFW',
 '14831': 'SJC',
 '14771': 'SFO',
 '13487': 'MSP',
 '12889': 'LAS',
 '12892': 'LAX',
 '12264': 'IAD',
 '13303': 'MIA',
 '11057': 'CLT',
 '13930': 'ORD',
 '14869': 'SLC',
 '10693': 'BNA',
 '10299': 'ANC',
 '12266': 'IAH',
 '11292': 'DEN',
 '12478': 'JFK',
 '14107': 'PHX',
 '14057': 'PDX',
 '10397': 'ATL',
 '13198': 'MCI',
 '11630': 'FAI',
 '12173': 'HNL',
 '10732': 'BQN',
 '11618': 'EWR',
 '14254': 'PSE',
 '13204': 'MCO',
 '10627': 'BIS',
 '11982': 'GRK',
 '12402': 'ITO',
 '14683': 'SAT',
 '10721': 'BOS',
 '11884': 'GEG',
 '15919': 'XNA',
 '13851': 'OKC',
 '11111': 'COU',
 '12191': 'HOU',
 '14783': 'SGF',
 '15016': 'STL',
 '12758': 'KOA',
 '13830': 'OGG',
 '10423': 'AUS',
 '15370': 'TUL',
 '11953': 'GNV',
 '13891': 'ONT',
 '15376': 'TUS',
 '11778': 'FSM',
 '11278': 'DCA',
 '14100': 'PHL',
 '15304': 'TPA',
 '11637': 'FAR',
 '11775': 'FSD',
 '12982': 'LIH',
 '13931': 'ORF',
 '10821': 'BWI',
 '14122': 'PIT',
 '10990': 'CHO',
 '13158': 'MAF',
 '14108': 'PIA

In [26]:
dict_airport.values()

NameError: name 'dict_airport' is not defined

In [ ]:
with open('dict_airport.json', 'wb') as fp:
    pickle.dump(dict_airport, fp)